### ISSUE TITLE
Keyless Driving...what am I doing wrong?

### ISSUE THREAD

**Issue by GeeRee1** [Kemmey/Kemmey-TeslaWatch-Public#106]
I have two Teslas on the app, which works fine for basic functions, unlocking, control, etc. 
However, I can’t seem to get keyless driving to work. I have the PW entered in the app, and whether the app is on cellular (LTE) or Bluetooth-synched with the phone, I need to “tap” the Keycard (or open the phone app to the desired car) to enable driving.  With Phone turned completely off & the car and watch connected to cellular, the car unlocks and all other controls work, but not keyless driving.  I’ve logged off, re-entered my Tesla PW (shows up as hidden “dots” in the PW field), but no help.  Does the watch need to be registered as a “key” in the car’s Lock Menu (like my phone and the key cards are)?
What am I doing wrong?
Otherwise, swell.  Thanks.

**Comment by Kemmey** [comment]
Hey,

Keyless driving still require you to activate the ignition from the app. 

What the watch app allows you to do, is when the feature has been enabled from settings, and your password stored, you can then remotely turn on the ignition and allow the car to be driven. It's not that the watch will magically function as an automatic key like your phone - that's impossible for 3rd party devs, as we do not have access to the Tesla Bluetooth keys. 

The watch app basically pushes this Tesla iOS app button:

![image](https://user-images.githubusercontent.com/4688084/91438166-3796dd00-e86b-11ea-9324-8946e6609d79.jpeg)

When you tap on controls and then keyless drive:

![image](https://user-images.githubusercontent.com/4688084/91438224-4aa9ad00-e86b-11ea-8660-cdbe12edabfb.jpeg)

**Comment by Kemmey** [comment]
The feature requests all used the terminology Keyless Drive - but I think that is a bit confusing. The proper name should be Remote Start - I'll change that wording to be more precise.

**Comment by GeeRee1** [comment]
You know when you miss something obvious, and feel kinda dopey?  I didnt realize there was a “Keyless Drive” button in the controls menu...once “pressed,” it works as it should. 
My Bad.
Remote Start might be better term, but I’d still have missed it.  🤓
Thanks
