### ISSUE TITLE
Unlock and activate keyless driving from one click

### ISSUE THREAD

**Issue by Roarers** [Kemmey/Kemmey-TeslaWatch-Public#114]
I read on a Tesla forum about an Android only app that allows you to press a single button to unlock and turn on keyless drive (or Remote Start as the latest version of your app now calls it).

Any chance of adding this function, perhaps as an option. (In addition to unlocking the charge port as you've already done - which is great!)

**Comment by Kemmey** [comment]
Sure - sounds like a great feature. I'll add it as a toggle under remote start in settings, to basically auto-enable on unlock. Sounds convenient!

**Comment by Kemmey** [comment]
@Roarers if you haven't joined the TestFlight beta, you can join here: 

https://testflight.apple.com/join/FdzFOLZv

The feature will ship to TestFlight in about 30 mins :-D

**Comment by Kemmey** [comment]
Just tested this morning - works beautifully! :-D 

Thanks for suggesting!

**Comment by Roarers** [comment]
Hej Kim, thank you for being so responsive. I'm glad you thought it was a good idea and impressed you got it implemented so quickly. While I've used TestFlight once before, it was on an older phone, and I'm not familiar with using it on my watch. I'll happily wait a while until the next formal update.

Wishing you well.

**Comment by Kemmey** [comment]
Fixed in released 1.0.7
