### ISSUE TITLE
Can't log in with token

### ISSUE THREAD

**Issue by jordanmerrick** [Kemmey/Kemmey-TeslaWatch-Public#125]
I've been unable to log in with a token, though user/pass works fine. This is the error I get. 

![7A3458E3-F7F8-4FF5-9FAA-23FB0852D555](https://user-images.githubusercontent.com/1397671/92548946-14761100-f20d-11ea-9ace-679ae585800c.png)

I'm using the shortcut provided by your FAQ. I'm logged in using user/pass now. My password is complex and has special characters. Any ideas why I get a length error?

**Comment by RogerHungYi** [comment]
@jordanmerrick 
Hi,
I think you cope the hole sentence, as my experience, there will be four words in front of the token that shows up as "qtr-".
You need to delete those words to use the token.

**Comment by Kemmey** [comment]
Hmmm - maybe the token shortcut has been modified since I wrote that guide? It's quite unfortunate if it's not copying the token correctly. But yeah, as @RogerHungYi said, the token should just be one uniform string of only letters and numbers - no special chars or spaces. And it must be exactly 64 chars long to be valid

**Comment by jordanmerrick** [comment]
I've tried a couple of shortcuts and they were indeed including the prefix, though the prefix I was getting was `qtr-`. Removing that prefix does result in a 64 char long token but attempting to use it results in the error `Error: token did not work as either access token or refresh token`.

**Comment by jordanmerrick** [comment]
I have, however, since been able to log in using user/pass. I'd prefer to use the token though but can confirm I at least am able to use the app.

**Comment by Kemmey** [comment]
I can reproduce. 

It appears the the Tesla auth api has changed and is now issuing tokens with the prefix for access_token. However, refresh_token is still the correct token format. 

I'll have to debug this and possibly modify the auth form to accept these new tokens if they are accepted by the api. 

In the meantime, please try changing your shortcut to give you the refresh_token and try using that instead.

**Comment by jordanmerrick** [comment]
Sure, will try that. What's the difference in functionality between refresh and access tokens?

**Comment by Kemmey** [comment]
The access_token has a time to live if 45 days. After that you'll have to generate a new one. The refresh_token is a single use token that can be exchanged for an access_token and a new refresh_token. When the access_token is no longer valid, the app will use the refresh_token to get a new access_token automatically, giving you a perpetual uninterrupted login experience.

**Comment by jordanmerrick** [comment]
Thanks Kim, really helpful. I've successfully used the refresh token and logged in. From your description, I shouldn't have to log in or generate a token again.

If the access token is only valid for 45 days, what's the benefit of using that over a refresh token with the app? And if I was super paranoid and wanted to cut off the app's access to my Tesla account, can I revoke the token or access privilege?

**Comment by Kemmey** [comment]
Really good questions!

If you were quite paranoid, you'd only use the access token, because it has a limited lifespan. So you know that the access will eventually time out. 

If you want to kill access immediately you'd have to change your password. That instantly invalidates all issued tokens of all kinds.

**Comment by jordanmerrick** [comment]
Thanks again! Knowing that resetting my password would invalidate any tokens issued is good to hear.

**Comment by GeeRee1** [comment]
App-lover but tech-novice question: If the password to the Tesla account is encrypted and stored ONLY on the watch (not with the app developer or the world), what’s the advantage to using a token rather than the PW? I use the latter and it’s worked fine from the start. Just asking for a friend 😉

**Comment by jordanmerrick** [comment]
Paranoia more than anything :) from the app's website:

> You can either login with your username and password - or you can login with an auth token. You only need one or the other. The auth token is a bit of a nerd/paranoid-feature where you can generate the authentication token for the Tesla API yourself and supply just that, knowing that the app will never have seen your Tesla username and password

**Comment by Kemmey** [comment]
@jordanmerrick @GeeRee1 exactly! With the user/pass a malicious app could collect those and use them for abuse - they will grant full access to the account on Tesla.com and allow purchase of FSD etc. 

Now, in my app, this is never stored - they're used just once for getting the token. Optionally the password can be stored for remote start - but the username is still missing. 

That's the sound reason for some paranoia.

**Comment by GeeRee1** [comment]
Now I’m more confused and paranoid than usual.  If I were able to figure out where to get the refresh token, where and how to copy and paste it within the app, I suppose I’d do that.  The link in the FAQ for token access isn’t terribly clear to non-techies as to where to download it to.  Sigh.

**Comment by Kemmey** [comment]
Token login is really a solution for the paranoid tech savvies out there. User / pass achieves the exact same thing - and I can assure you, I do not collect nor even store that information in the app.
