### ISSUE TITLE
Request: Option to change the 3 top control icons

### ISSUE THREAD

**Issue by BjornB2** [Kemmey/Kemmey-TeslaWatch-Public#130]
Currently it's AC, Frunk and Lock, but I never use the frunk at all. I would much prefer to see the Trunk there. I guess everyone has his preference, so I think it would be really great to be able to choose which icons to show there. Or just change it to AC, **T**runk and Lock of course 😉

**Comment by Kemmey** [comment]
Join the beta here: https://testflight.apple.com/join/FdzFOLZv

Already implemented for 1.0.7 :-D

**Comment by BjornB2** [comment]
Ah awesome 😃

**Comment by Kemmey** [comment]
Fixed in released 1.0.7
