### ISSUE TITLE
Interval in 1.0.7 not persistant

### ISSUE THREAD

**Issue by BjornB2** [Kemmey/Kemmey-TeslaWatch-Public#132]
Hi

When I set the interval to 1 hour, go back and then enter the settings again it's back on 15 minutes. I guess the value is not properly saved. 1.0.7 build 263

Björn

**Comment by Kemmey** [comment]
Did you tap the set button after making the change?

**Comment by BjornB2** [comment]
No. Didn't notice that I should. Maybe partly because of the translation on this button, partly because I wasn't expecting it, and partly because it doesn't really look like a button. 
When I do press the button it does work fine though 😁
