### ISSUE TITLE
Can’t reinstall 

### ISSUE THREAD

**Issue by afeldman6** [Kemmey/Kemmey-TeslaWatch-Public#133]
I’ve tried everything recommended on this site but I just see a greyed-out “purchased’. Anything I can do to reinstall?

**Comment by Kemmey** [comment]
Have you done it from the watch?

**Comment by afeldman6** [comment]
Just re-read your instructions and was able to do it from the watch. Thanks for getting back to me so promptly.

Alan M. Feldman
Sent from my iPhone

On Sep 13, 2020, at 2:05 PM, Kim Hansen <notifications@github.com> wrote:

﻿

Have you done it from the watch?
