### ISSUE TITLE
watchOS7 and Watch App for Tesla

### ISSUE THREAD

**Issue by sa012** [Kemmey/Kemmey-TeslaWatch-Public#136]
I purchased this app 3 months ago and it worked fine.  I had to repair my watch for watchOS7 and now the app is gone and I can’t redownload it.  It shows that it is purchased in App Store on phone but not showing up as purchased in App Store for Apple Watch.  Showing $5.99.  Not sure if maybe app not supporting watchOS7 yet? Please help. Thx

**Comment by BriarReed** [comment]
Same problem. Updated Series 4 watch to OS7.0. I unpaired and then re-paired with iPhone, which was recently updated to OS14. The app doesn’t appear in the iPhone watch app. I went to the App Store and it shows as being downloaded. Did I do something wrong or do I wait for a fix? Thanks

**Comment by BriarReed** [comment]
Problem solved, Had to reinstall the app from my watch.

**Comment by Kemmey** [comment]
@sa012 if you're logged in to the same Apple ID on your watch as you used to purchase the app, it will not bill you twice. When you try to "purchase" again, it will just let you know you've already purchased the app and download it again. 

If not, request a refund from Apple for the old purchase and continue with the new purchase on your new account.

**Comment by sa012** [comment]
Thank you.  Like you said it did not charge me.
