### ISSUE TITLE
Does this app support Model X?

### ISSUE THREAD

**Issue by mrscruple** [Kemmey/Kemmey-TeslaWatch-Public#139]
and if not is that a feature that is coming soon?

**Comment by Kemmey** [comment]
@mrscruple Yes, it does :-D 

But if you run into issues, please let me know. 

I've had requests to allow remotely opening and closing the doors, but I've not been able to find api support for that unfortunately.

**Comment by mrscruple** [comment]
Thank you Kemmey!

**Comment by beechcottage** [comment]
It works fine on my Model X EXCEPT Start/Stop charging doesn’t seem to work (though I don’t know whether thats specific to the S/X or not).

**Comment by Kemmey** [comment]
@beechcottage There was a bug a while bag in the vehicle software that prevented start stop from working. Please try to reboot your mcu and try again - please report back if successful

**Comment by beechcottage** [comment]
Hi Kemmey, tested start/stop charging - now works. Thanks!
