### ISSUE TITLE
Can not download. “Purchased” is greyed-out

### ISSUE THREAD

**Issue by appuser31** [Kemmey/Kemmey-TeslaWatch-Public#143]
Can’t download app. The status shows purchased by is greyed-out. 
Please advised

FYI: Had watch version before 7.0 and it work on my watch 3 perfectly fine but same issue when trying to add to my wife’s 5. 
Now that I’ve upgraded to 7.0, I can get it to load on my watch.

**Comment by Kemmey** [comment]
@appuser31 please try to download the app directly on the watch:

https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/5#issuecomment-658742571

Let me know if you're still having problems after that. 

For family sharing, you'll note that it says purchase, that's a bug on apples part: 

https://support.apple.com/en-us/HT201085#apple-watch

**Comment by appuser31** [comment]
Thank you. That worked.
By the way, really like this app.  Great job with its creation.

Sent from my iPhone, please forgive any typographical errors

On Sep 21, 2020, at 01:21, Kim Hansen <notifications@github.com> wrote:

﻿

@appuser31<https://github.com/appuser31> please try to download the app directly on the watch:

#5 (comment)<https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/5#issuecomment-658742571>

Let me know if you're still having problems after that.

For family sharing, you'll note that it says purchase, that's a bug on apples part:

https://support.apple.com/en-us/HT201085#apple-watch
