### ISSUE TITLE
Vehicle open warning for sunroof while driving

### ISSUE THREAD

**Issue by nachtbraker** [Kemmey/Kemmey-TeslaWatch-Public#146]
While driving with the sunroof open for a while, I will get an "Open features reminder" on my watch:

![IMG_2359](https://user-images.githubusercontent.com/29022937/93813509-83af2480-fc53-11ea-8c3e-9bad665b3212.png)

Currently running v1.0.7 build 272, but this issue has been in there for a while. I think it would be best to suppress this message while driving. (But it would make perfect sense if the car was parked.)

**Comment by Kemmey** [comment]
Whoops - good catch! I'll fix :-D same was true for plug-in reminder...

**Comment by Kemmey** [comment]
Fixed in released 1.0.7
