### ISSUE TITLE
Unable to set settings

### ISSUE THREAD

**Issue by jasonhermosa** [Kemmey/Kemmey-TeslaWatch-Public#15]
Just got the app today and was able to login using the token. I tried looking for keyless drive but don't see the option anywhere. The settings button at the bottom of the watch app is greyed out.

**Comment by Kemmey** [comment]
Hey

Tap the settings button :-D 

It is grayed out to not impose in daily use - it is not deactivated.

**Comment by jasonhermosa** [comment]
Thanks. I was able to click on it. Are you guys taking backlog requests? Can we request for the small modular screen to have different options? I use another app called Automate and they were able to integrate the battery percentage with the lock status of the car in one small modular component.
![IMG_7098](https://user-images.githubusercontent.com/67345415/85482339-ebcc6c80-b577-11ea-945a-cd6b83dc35bc.PNG)

**Comment by lcharette** [comment]
I second the complication. The big percentage is not the most esthetic complication. I like the lock option. It could also be the Tesla logo instead of the lock if it's easier.

**Comment by Kemmey** [comment]
Thanks for the feedback, which is absolutely most welcome!

I must admit that I've focused on the graphic corner complication, as that is able to fit the most data in. 

I'll definitely try to rework some of the other complications, though I must admit, my primary focus for now will be to show the SoC in percent and as a guage and then if possible, a charging indicator, sentry active indicator, open features indicator and charge time remaining as live countdown. Those are the complication data that I find most useful. 

The lock indicator - though useful - can be misleading, as the complication can lag behind up to an hour - or more depending on connectivity or preferences.

But with all the new stuff being announced this week for watchOS 7, I will look into exposing more than one complication type in the fall - and I'll keep this feedback in mind for then :-D

**Comment by indiprod** [comment]
> The settings button at the bottom of the watch app is greyed out.



> Hey
> 
> Tap the settings button :-D
> 
> It is grayed out to not impose in daily use - it is not deactivated.

On my watch the settings button seems to be deactivated.  Just installed the app and love it, but when I tap the greyed out settings button, nothing happens.  Suggestions?

**Comment by Kemmey** [comment]
@indiprod yeah - there's a super annoying bug in the current 1.0.4 app store release on Series 3 and below watches, where the settings button is cut off at the bottom.

I have a fix ready, but it will take a couple days to get it through app review. 

In the meantime, it should be possible to scroll with the crown and then tap while the button is visible, or just tap vigorously at the very bottom of the screen - then you'll eventually succeed in hitting the button.

**Comment by jasonhermosa** [comment]
> In the meantime, it should be possible to scroll with the crown and then tap while the button is visible, or just tap vigorously at the very bottom of the screen - then you'll eventually succeed in hitting the button.

This is where I'm at right now. Desperately trying to hit the settings button.

**Comment by jasonhermosa** [comment]
> I must admit that I've focused on the graphic corner complication, as that is able to fit the most data in.

We saw that and it looks great. Unfortunately, the corer graphic only applies to watch 4 and 5 and doesn't leave much love for my 3 and my gf's 2.

**Comment by Kemmey** [comment]
@jasonhermosa I'll see what I can do to improve the classic complications - if there's a quick win, I'll do it of course :-D

**Comment by Kemmey** [comment]
I reworked some of the classic complications. The modular one is still annoying - it will now switch between showing the SoC in percent with a ring or range + unit depending on preferences in the car. The utilitarian ones are actually not too bad, and can carry quite a lot of info!

![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-06-26 at 23 48 03](https://user-images.githubusercontent.com/4688084/85903809-87274100-b807-11ea-9fb5-0a1c2ac2e5e7.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-06-26 at 23 48 09](https://user-images.githubusercontent.com/4688084/85903812-88586e00-b807-11ea-91c9-ed0bf25d34c3.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-06-26 at 23 47 59](https://user-images.githubusercontent.com/4688084/85903814-88f10480-b807-11ea-8c84-64b71ef29a2c.png)

**Comment by indiprod** [comment]
> @indiprod yeah - there's a super annoying bug in the current 1.0.4 app store release on Series 3 and below watches, where the settings button is cut off at the bottom.
> 
> I have a fix ready, but it will take a couple days to get it through app review.
> 
> In the meantime, it should be possible to scroll with the crown and then tap while the button is visible, or just tap vigorously at the very bottom of the screen - then you'll eventually succeed in hitting the button.

Series 4, watchOS 6.2.6.  My display shows the greyed-out settings button no problem.  I've tried for two days to get the button to work, tapping vigorously every which way per @Kemmey's suggestion, nothing happens.  I see it's now flagged as a bug.  Does the 1.0.5 release fix this?  Nice work on latest complications.

**Comment by lcharette** [comment]
Thanks for the complications! The modular one is indeed not perfect, but better IMO than the big percentage.

For the setting button, I agree on a UX stand on point, it shouldn't be grey out.

**Comment by Kemmey** [comment]
@indiprod hmmm, the defective settings button bug only applies to the series 3 and below. 

I've not done anything I particular to change it for the s4-5 watches. 

Could you try the TestFlight build and check if it works in the latest build?

https://testflight.apple.com/join/FdzFOLZv

It works fine on my s5 44 and also in the simulators of all sizes and series.

**Comment by Kemmey** [comment]
@lcharette fair enough - it started out as an easter egg as the app logo that you could tap, akin to the Tesla logo in the cars. But as more and more stuff was added there, it was relevant to make it more discoverable. I'll make it come full circle and become a Norma button... :-D

**Comment by jasonhermosa** [comment]
> @indiprod hmmm, the defective settings button bug only applies to the series 3 and below.
> 
> I've not done anything I particular to change it for the s4-5 watches.
> 
> Could you try the TestFlight build and check if it works in the latest build?
> 
> https://testflight.apple.com/join/FdzFOLZv
> 
> It works fine on my s5 44 and also in the simulators of all sizes and series.

Just tried the latest testflight version on Series 3 and the settings button shows up now.

**Comment by indiprod** [comment]
> https://testflight.apple.com/join/FdzFOLZv

The Testflight version has the settings button greyed-out and working on my Series 4.   @jasonhermosa you might want to try this.

**Comment by Kemmey** [comment]
@indiprod next build coming in a couple mins will make it a full normal button, and not grayed out anymore... :-D

**Comment by indiprod** [comment]
@Kemmey Is that a Testflight build, or App Store build?  Want to know how to update.

**Comment by Kemmey** [comment]
@indiprod testflight :-D

**Comment by indiprod** [comment]
Testflight 1.0.5 build 140 shows full normal settings button and it works. :)

**Comment by Kemmey** [comment]
Awesome!

Too bad Apple just rejected the update. 

They've apparently changed their mind since yesterday about allowing Tesla apps in their store. 

App update rejected for using Tesla API. Literally. With all the news about Apples review guidelines lately, you'd think they'd be a bit more welcoming? But no - reject an app with nothing but bug fixes... 

I so so so hate apple app review :-(

**Comment by jasonhermosa** [comment]
Same. Settings button shows up as a normal button now. 

Whaaat? Why are they rejecting tesla api apps?

**Comment by Kemmey** [comment]
They reject Tesla apps because they use the Tesla API, which none of us have the proper rights to access. 

In fairness, they are right to reject it, however there are already a lot of apps in the store, so my problem is that they are arbitrarily rejecting some apps and not others, clearly indicating the review process is broken. Besides, Tesla doesn't seem to mind - the community around Tesla is extremely supportive and protective of the company - I believe Tesla appreciates that. 

Anyway - after I appealed and pointed out the app reviewers hypocrisy, they approved the build last night...

Which means, 1.0.5 is live in the store now...
