### ISSUE TITLE
Siri won’t work

### ISSUE THREAD

**Issue by ARTesla** [Kemmey/Kemmey-TeslaWatch-Public#157]
I tried using Siri and I get this note on my watch. How do I fix this?
![9B9E1FAD-2AFB-45BC-8871-614B987EEB67](https://user-images.githubusercontent.com/72288207/94981328-5e49d280-04ff-11eb-9a23-6fb5e9715599.jpeg)

**Comment by Kemmey** [comment]
Open Settings app on your watch, then navigate to Siri, Use with Siri and enable Watch for Tesla

**Comment by ARTesla** [comment]
Great Customer Service. Thank you.
