### ISSUE TITLE
Can't Reinstall App

### ISSUE THREAD

**Issue by jasonhermosa** [Kemmey/Kemmey-TeslaWatch-Public#16]
I ended up having to delete the app on the watch and now need to reinstall it. Problem is, I can't find it. 

If I go to the appstore on the phone, it says that it's Purchased. No download button. If I go to the appstore on the watch, the app doesn't show up on my list of purchases. The app doesn't show up in the Watch app on my iPhone either. 
![IMG_B5FC0B80EEAB-1](https://user-images.githubusercontent.com/67345415/85607815-537ec800-b609-11ea-81d3-7c8ed22570ee.jpeg)
![IMG_BE098D42702C-1](https://user-images.githubusercontent.com/67345415/85607862-5e395d00-b609-11ea-857b-5188712d0979.jpeg)

![IMG_CDE508664FEE-1](https://user-images.githubusercontent.com/67345415/85607664-2e8a5500-b609-11ea-9558-e36395e3ea75.jpeg)
![IMG_7122](https://user-images.githubusercontent.com/67345415/85607679-31854580-b609-11ea-9261-2e53dfafc4f3.PNG)
![IMG_7120](https://user-images.githubusercontent.com/67345415/85607680-31854580-b609-11ea-98fa-eedbfed5ff1b.PNG)

**Comment by Kemmey** [comment]
Wow - that's a new one... 

I would really like to be able to help, but this is entirely in Apples hands. Making sure that experience works and is easy for customers to use and understand, is why they take their 30% cut. 

I'm not sure I agree that they live up to their end of that bargain...

All I can do is direct you at Apple AppStore support and ask them wth is going on here :-(

**Comment by aggiemike88** [comment]
I encountered same thing but solved it....

To download again, you need to search the Watch App Store using your Watch,  to the phone.   Once you land on the Watch App for Tesla "page", you should see the icon for downloading a previously purchased app.

**Comment by jasonhermosa** [comment]
> To download again, you need to search the Watch App Store using your Watch, to the phone. Once you land on the Watch App for Tesla "page", you should see the icon for downloading a previously purchased app.

This resolved it. Thanks @aggiemike88
