### ISSUE TITLE
Force language to english?

### ISSUE THREAD

**Issue by gurenius** [Kemmey/Kemmey-TeslaWatch-Public#162]
I'd like to use english as language but can't find a way to change it.

**Comment by Kemmey** [comment]
The app picks up the language of your watch. Unlike iOS, apps cannot change language independently so you need to change the language of the watch itself.

**Comment by Kemmey** [comment]
In watch app on iOS go to My watch, General, Language & Region and there change Watch Language or change your preferred language order

**Comment by gurenius** [comment]
Fast reply. Impressive! Ah, I'll consider changing the Watch or maybe open a pull request for the Swedish translations. :-)

**Comment by Kemmey** [comment]
A PR with Swedish translations would be awesome! They are here: https://github.com/Kemmey/Kemmey-TeslaWatch-Public/blob/master/Localizations/sv.lproj/Localizable.strings

:-D
