### ISSUE TITLE
Support for two-factor authentication

### ISSUE THREAD

**Issue by jordanmerrick** [Kemmey/Kemmey-TeslaWatch-Public#163]
I'm sure it's too early to tell but wondering if the app will support Tesla's new rollout of 2FA? I'd like to enable it but wondering what impact it'll have on my ability to use the app.

**Comment by Kemmey** [comment]
I assure you, all 3rd party Tesla app developers are currently scrambling to add support. Top priority!

I have mfa enabled on my private account - so far the old auth endpoints still work, which I take as Tesla giving us a grace period to get it done.

**Comment by jordanmerrick** [comment]
Thanks!

**Comment by Kemmey** [comment]
CC'ing the main work being done by Tim Dorr here https://github.com/timdorr/tesla-api/issues/215
