### ISSUE TITLE
Lost app

### ISSUE THREAD

**Issue by popsiclepap** [Kemmey/Kemmey-TeslaWatch-Public#165]
I just repaired my watch and the Tesla Watch app is gone from my phone and watch. When I got to the App Store it shows the app purchased but grayed out. How can I get it back?

**Comment by Kemmey** [comment]
You need to do it from the watch

https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/5#issuecomment-658742571

**Comment by popsiclepap** [comment]
Thank you, it worked
