### ISSUE TITLE
Tesla-Account: Two factor authentication

### ISSUE THREAD

**Issue by bluefire100** [Kemmey/Kemmey-TeslaWatch-Public#167]
How does "Watch for Tesla" use the new feature "Two factor authentication" ?

**Comment by Kemmey** [comment]
Cc https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/163

So far the old APIs still work. I gave mfa enabled on my own account. I'm actively working on support, but so far everything still works even with mfa enabled.
