### ISSUE TITLE
Keyless Drive password and Homelink

### ISSUE THREAD

**Issue by damir233** [Kemmey/Kemmey-TeslaWatch-Public#19]
Hello. I was able to login with my initial Tesla credentials without issue. 

When attempting to set the keyless drive I can input the password. Nothing happens. It just gives me option to delete out info and type in password again. 

I have a cellular Apple Watch. What should I do to enable this? 

I also have homelink with the car but it does not show as option in the watch app. Anything that needs to be done to enable this?

**Comment by Kemmey** [comment]
Hey,

In settings, all you do is enable the feature, by inputting your password. To actually activate keyless drive - which then will not require your password each time - you have to activate it from either the force touch menu or the controls menu - both from the main screen :-D 

Regarding Homelink - unfortunately Tesla require FSD to remotely trigger Homelink. Can you confirm if you have FSD?
