### ISSUE TITLE
Watch app works on cellular?

### ISSUE THREAD

**Issue by ibmaster** [Kemmey/Kemmey-TeslaWatch-Public#20]
Nice little watch app for my 2 Teslas! :)
I have a cellular enabled Apple Watch, but refresh seems to be having issues when not paired with my phone... is watch only cellular connectivity officially supported?

**Comment by Kemmey** [comment]
Hey,

Yeah, watch only is most definitely supported - I use it myself now and then.

Did you check that the watch did manage to switch over to LTE from control center? Often that can take a couple of minutes.

**Comment by ibmaster** [comment]
Thanks I guess I must have been testing it out in a bad cellular signal area.

**Comment by Kemmey** [comment]
@ibmaster btw, having more than one vehicle, just a tip - set background image url to "https://static-assets.tesla.com/v1/compositor/" without the quotes and enable the querystring option in settings, and enjoy custom backgrounds and vehicle chooser images for each vehicle :-D

Of course - that's not me telling you this officially, as I can't legally use those image resources - but I can't control what url you might enter into the app :-D
