### ISSUE TITLE
Problem version iOS

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Kemmey/Kemmey-TeslaWatch-Public#205]
Problem install version for iOS 

![image](https://user-images.githubusercontent.com/5438823/98488240-49f8a400-2228-11eb-8d85-f39850138295.png)

**Comment by Kemmey** [comment]
OMG! Same for me. This is exactly what I feared, that Apple would fuck this up, as they did with the TestFlight install. Only the store does not even allow install when app is completely removed! :-(

I'll have to contact Apple developer support and have them look into it. Most likely, they've never had an independent watch app add an iOS app before...

**Comment by Kemmey** [comment]
@SiNaPsEr0x Try now? It just started working for me, showing the cloud download button :-D

**Comment by SiNaPsEr0x** [comment]
I request refund and repay after... I think is only solution

**Comment by SiNaPsEr0x** [comment]
With staff Apple i fix it!

**Comment by Kemmey** [comment]
@SiNaPsEr0x Could you elaborate?

**Comment by SiNaPsEr0x** [comment]
I contact link of refound but i esplicate the problem.... and they fixing it

Inviato da iPhone
