### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Peter2169** [Kemmey/Kemmey-TeslaWatch-Public#209]
I have been trying to login on Apple Watch 6, iOS 7.1, unable to login with User ID and Password. I tried token, not working either. 
Error Code: 848, SSL Error.

**Comment by Kemmey** [comment]
@Peter2169 hmm - that's interesting. There's something in the network between your watch and Teslas auth servers that intercept the SSL traffic and invalidates the encryption. 

Could you try logging in from the iOS counter part app that was added in version 1.0.8 - that login flow is using the new modern multifactor auth flow in a webview popup, same as the official tesla app. 

Also, try disabling wifi - might be corporate wifi that is interfering?

Let me know if that did the trick.

**Comment by Peter2169** [comment]
i tried with iOS counter part app, successfully logged in. And Watch App logged in now.
Thank you for the quick resolution.
