### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by drrob423** [Kemmey/Kemmey-TeslaWatch-Public#21]
unable to enter url in apple watch keyboard. Also not able to enter url on my iphone.

**Comment by Kemmey** [comment]
Hey,

Yeah, connectivity keyboard experience is really bad. 

If it doesn't show up at all on phone, check Notification Center or disable do not disturb. 

If you can't paste, you have to use the new three-finger-tap gesture inside the text input field. 

Can you verify if either of those helped?

**Comment by ibmaster** [comment]
It worked for me using scribble. (Yes copy/paste would’ve been nice but probably an iOS limitation?)
Thanks for the pro tip! Nice to have those backgrounds for the cars :)

**Comment by pcase1999** [comment]
how would I be able to get my model s image as the background please?

**Comment by Kemmey** [comment]
@pcase1999 add "https://static-assets.tesla.com/v1/compositor/" without the quotes as your background image url and toggle on the querystring option - then the app will do the rest :-D 

If you have a series 3 or below watch, please not that there is currently a bug that makes it extremely hard to access settings - you have to tap at the bottom of the screen a lot, eventually it should register. I'll have a fix out for that ASAP!

**Comment by pcase1999** [comment]
> @pcase1999 add "https://static-assets.tesla.com/v1/compositor/" without the quotes as your background image url and toggle on the querystring option - then the app will do the rest :-D
> 
> If you have a series 3 or below watch, please not that there is currently a bug that makes it extremely hard to access settings - you have to tap at the bottom of the screen a lot, eventually it should register. I'll have a fix out for that ASAP!

Worked thanks.

**Comment by drrob423** [comment]
Yes this worked. Thank you

Sent from my iPhone

On Jun 26, 2020, at 8:49 AM, pcase1999 <notifications@github.com> wrote:

﻿
@pcase1999 add "https://static-assets.tesla.com/v1/compositor/" without the quotes as your background image url and toggle on the querystring option - then the app will do the rest :-D

If you have a series 3 or below watch, please not that there is currently a bug that makes it extremely hard to access settings - you have to tap at the bottom of the screen a lot, eventually it should register. I'll have a fix out for that ASAP!

Worked thanks.
