### ISSUE TITLE
Insomnia again

### ISSUE THREAD

**Issue by dapper27** [Kemmey/Kemmey-TeslaWatch-Public#211]
Last few days I've noticed my car not sleeping. At first I thought it might just be having installed the 2020.44 update but I had two full days with the car failing to sleep for anything more than a few minutes at a time.

I changed my Tesla password (I don't use 2FA yet) and within about 15 minutes car started sleeping normally again.

I've gradually logged into other things and narrowed it down to Watch App. I've just logged out on both the companion app and the watch and within about 15 minutes the car is sleeping soundly again.

Is it possible a regression could have crept in that keeps the car awake intermittently? I had all the background checking switched off by the way.

**Comment by Kemmey** [comment]
@dapper27 I've not touched anything in the backgrounding code for a while. If you go to settings, scroll to bottom and then tap on show debug, and scroll to bottom again, you should be able to see timestamps within the past 24 hours for wake events - and now also token events. Try and compare that to what you expected...

**Comment by dapper27** [comment]
Is that debug on the watch or the iOS companion app? Or do both do the same?

**Comment by Kemmey** [comment]
@you need to check both separately - they run completely independently except for the token exchange

**Comment by Kemmey** [comment]
@dapper27 the iOS app does not do any sort of backgrounding, btw.

**Comment by dapper27** [comment]
Can confirm the insomnia stopped being a problem. Happy to close issue.
