### ISSUE TITLE
Using Siri on iWatch

### ISSUE THREAD

**Issue by MarsTsip** [Kemmey/Kemmey-TeslaWatch-Public#214]
Hi,
Just trying to determine how to use Siri to unlock the car. I have tried “Hey Siri, unlock the Tesla” but it doesn’t recognise the command.

Thanks
Marinos

**Comment by Kemmey** [comment]
Hey @MarsTsip 

I'll add documentation for this at some point - priority is adding features and stabilizing at this point, though...

Refer to this comment for apples documentation of the four Siri commands I've implemented: 

https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/210#issuecomment-725423350

**Comment by ziskend** [comment]
“Hey Siri unlock the car” has worked for me.

**Comment by MarsTsip** [comment]
Hi All,

Just an update how this was resolved:

- I deleted the app from my iWatch.
- I was on iOS 14.1, and upgraded to 14.2
- Re-installed the app from my phone.
- Both phone and iwatch app were installed.
- Activated Siri from Settings.

All working perfectly.

Thanks,
Marinos
