### ISSUE TITLE
allow wake - can't disable "always"

### ISSUE THREAD

**Issue by pjones123** [Kemmey/Kemmey-TeslaWatch-Public#233]
In the new phone app, I've changed wake to select active hours and interval to 1.5 hours, but it always returns to "always" and 1 hour immediately.

**Comment by Kemmey** [comment]
Did you tap the set button to store the changed setting?

![image](https://user-images.githubusercontent.com/4688084/100913945-baff4480-34d2-11eb-975d-826ea92ca07b.jpeg)

**Comment by pjones123** [comment]
thanks, it wasn't particularly clear that that was a button, but it's working now.
