### ISSUE TITLE
Remote start/Keyless drive toggle not available 

### ISSUE THREAD

**Issue by kleine100** [Kemmey/Kemmey-TeslaWatch-Public#246]
Hey Kim,
The keyless drive feature is not available on my Apple Watch. I have logged in on the iPhone Watch for Tesla app and transferred the login info to the app on the Apple Watch. When I then go to settings on the app on the Apple Watch there is no toggle called Keyless drive (Remote start). What am I doing wrong?

**Comment by Kemmey** [comment]
Hey @kleine100 if the toggle is missing from settings, it is because the car is reporting the feature as not supported. 

You most likely have to enable it in the vehicle itself. 

Check the official Tesla app and ensure you can enable it there first - then the watch should pick it up and show the toggle in settings.  

Once enabled in settings, ensure to type in your password in the text box below the toggle. Triple check you do not have any typos! Then the remote start button should show up under controls.

**Comment by Kemmey** [comment]
Btw, the password automatically transfers across to the watch if you have iCloud Keychain enabled - in which case it is much easier to input the password in the iOS companion app :-D

**Comment by kleine100** [comment]
I cannot enable from the official Tesla app. I can only see I have setup my iPhone as Phone Key. 
Will check if I can enable in my vehicle in the morning. 

I use the ICloud Keychain to transfer login. Btw it seems you can only logout on your Apple watch, when you have logged out from the IOS companion app on the phone.

**Comment by kleine100** [comment]
Hey again. Just activated the keyless driving from the car and now the toggle shows on the watch app. :-)

One last question. The auto-enable remote start feature, does that need to be set as ‘On’?

Thanks for the fast support :-)

**Comment by Kemmey** [comment]
Hey @kleine100 

Auto enable does not have to be active. In fact, I advise against it. But if you do enable auto activate, then when you tap the unlock button in the watch app, or by using the complication action, you'll unlock the car, unlock the charge port latch and start the car - all from one tap. So it's super useful if your daily routine require those three actions :-D

**Comment by Kemmey** [comment]
Though for most people with model 3/y, the Bluetooth phone key will take care of all three actions, so it's less useful on those cars...

**Comment by kleine100** [comment]
Thanks Kim. 
I can see the risk of having auto enable active, as that would leave the car totally unprotected in case you accidentally unlock your car. :-) Think I will start out by deactivating this feature to be safe ;-)
