### ISSUE TITLE
SuperCharging status - missing kW & A data?

### ISSUE THREAD

**Issue by ibmaster** [Kemmey/Kemmey-TeslaWatch-Public#25]
Not sure if this is a limitation from what Tesla's API provides, but when SuperCharging, the app reports the estimated time remaining, current battery voltage and the total kWh added... but not the actual instantaneous power (kW) or amps into the battery. Those fields both always remain 0.
If it's a Tesla API issue, maybe remove those fields from the app when SuperCharging?

**Comment by Kemmey** [comment]
Absolutely - and fixed in 1.0.5 beta, which you can join here to verify :-D 


https://testflight.apple.com/join/FdzFOLZv

**Comment by ibmaster** [comment]
sweet, installed the beta… thanks! 
My SuperCharging is done for now but will verify this update in v1.0.5 beta the next time I SuperCharge.
