### ISSUE TITLE
Disonnect

### ISSUE THREAD

**Issue by yuckyhd1** [Kemmey/Kemmey-TeslaWatch-Public#252]
Apologies. New user. Help appreciated for proper settings so that the watch for Tesla app only becomes active when I open it on my watch or cell phone. I don’t want it polling the car for status unless I tell it to regardless of it being charged or disconnected from the charger. I might already have it right as I have disabled “Background updates”. Is that all there is to it ??

**Comment by Kemmey** [comment]
@yuckyhd1 Yub - that's all there is to it :-D

**Comment by yuckyhd1** [comment]
Thank you. Terrific app.
