### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by ran251** [Kemmey/Kemmey-TeslaWatch-Public#26]
Have purchased app 3 times and will not download. Shows purchased in App Store but doesn’t show up on watch or iPhone. Purchased notation shows up subdued on App Store.  Won’t show up purchased on account in App Store on watch. Have latest watch is installed.

**Comment by Kemmey** [comment]
Hey,

Please see this item in the FAQ:

I bought the app, but it is not installing to my watch?

Try opening the AppStore on your watch - scroll all the way to the bottom and tap on "Account" then on "Purchased" then on "My purchases" (skip this step if not enrolled in an Apple family account) and then find the app and tap on the cloud icon - the app should install then. When finished, tap on open to open up the app.

Important to note - this has to happen directly on the watch, NOT the watch app on your phone.

Please let me know if that worked for you!

**Comment by Kemmey** [comment]
Just re-read your comment - I figure you are already doing it directly on the watch. 

Hm, that's extremely strange. 

Are you per chance running two different accounts for the store? Have you purchased the app directly on the watch App Store? What is the app status in the watch App Store - can you send a screenshot from the watch?

Last resort: restart both phone and watch...

**Comment by Kemmey** [comment]
Just saw a comment in a closed issue, that you might be able to fix by searching the App Store directly on the watch for the app, and then be able to download from the store listing on the watch. 

Why it doesn't show up on your actual purchased tab in the store app is beyond unreasonable, but do try that workaround...
