### ISSUE TITLE
CHARGE LEVEL

### ISSUE THREAD

**Issue by yuckyhd1** [Kemmey/Kemmey-TeslaWatch-Public#260]
Hello. Today I used my apple watch and the TESLAWATCH app to set the charge level to 80%. It was previously set at 56% - which is where it ended up .IE: resetting the charge to 80% didn't work. This is second time that happened. I thought it was just me the first time. maybe I didn't do it right...but it seems that there's a glitch here. Or perhaps I'm missing something.

Please advise.
thanks.

**Comment by Kemmey** [comment]
@yuckyhd1 Did you tap the set button after making the change? The value is not stored until you do

**Comment by yuckyhd1** [comment]
Coincidentally, I just figured that out !

And , thank you so much for the prompt reply. 

BDEU.    Apologies.
