### ISSUE TITLE
Face on watch with info like e.g. sentry mode

### ISSUE THREAD

**Issue by larsoeh** [Kemmey/Kemmey-TeslaWatch-Public#27]
Hi,
How do I get a face on my watch like the one in app-store?

Regards
Lars
![Screen Shot 2020-06-26 at 18 20 10 ](https://user-images.githubusercontent.com/7272057/85879387-8fb55280-b7da-11ea-9e20-8d1ae2880789.png)

**Comment by Kemmey** [comment]
That's the Infograph watch face, exclusively available on series 4 and 5

**Comment by larsoeh** [comment]
Thanks a lot.
This is a great app. Thanks a lot for fast response.

Regards,
Lars
