### ISSUE TITLE
444 Client Error

### ISSUE THREAD

**Issue by jpbjerke2020** [Kemmey/Kemmey-TeslaWatch-Public#272]
Trying to login using tesla credentials on alle watch app(confirmed user/pass). Getting "could not acquire token. Request failed. Response code: 444. Message: Client error"

**Comment by jpbjerke2020** [comment]
![85B34B23-C4C6-414C-A92C-A577AB2E09AF](https://user-images.githubusercontent.com/77990089/105757433-3e2a9d00-5f4e-11eb-8787-87eee8f2007b.jpeg)

**Comment by jpbjerke2020** [comment]
Last development on Tesla app...

**Comment by Kemmey** [comment]
Hey @jpbjerke2020 

So I gather from the above that you experienced the same error in the official Tesla app, and concluded it was a Tesla server issue?

I tried to reproduce, but was unable. 

Has it since been fixed for you too?

**Comment by jpbjerke2020** [comment]
Hiya!

Yep, was completely f***ed. After attemtimg to login several times it screwed up my ordinary tesla app as well. 30 minutes later, was ablo to login to both in both apps.
Working great atm 😊

Fra: Kim Hansen <notifications@github.com>
Sendt: mandag 25. januar 2021 21:29
Til: Kemmey/Kemmey-TeslaWatch-Public <Kemmey-TeslaWatch-Public@noreply.github.com>
Kopi: jpbjerke2020 <jpbjerke@outlook.com>; Mention <mention@noreply.github.com>
Emne: Re: [Kemmey/Kemmey-TeslaWatch-Public] 444 Client Error (#272)


Hey @jpbjerke2020<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpbjerke2020&data=04%7C01%7C%7Cf2063e89259a4f04e3e408d8c16fd79c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637472033388422318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QWHPLQaFsoa72brUMw02G9OGU9rd28Bo6siScIUS3Io%3D&reserved=0>

So I gather from the above that you experienced the same error in the official Tesla app, and concluded it was a Tesla server issue?

I tried to reproduce, but was unable.

Has it since been fixed for you too?

**Comment by Kemmey** [comment]
Please keep me posted if you experience it again. I've just had news from another service that those 444 errors might be rate limits. I fear I might have a runaway auth thread running unchecked. 

Will investigate and check my rate limit code.
