### ISSUE TITLE
Not supported in watchOS 7

### ISSUE THREAD

**Issue by PacoCruz** [Kemmey/Kemmey-TeslaWatch-Public#29]
App or complication are not available in watchOS 7. Happy to help debug.

**Comment by Kemmey** [comment]
Hmm, several people are already running it on watchOS 7, I'm being told. 

Are you sure it's not just the annoying bug that independent watch apps not always auto-install?

Could you try downloading the app from the AppStore app on the watch itself?

I am, however, always looking for new testers, so please join the TestFlight here if you wish to help out! :-D 


https://testflight.apple.com/join/FdzFOLZv

Please indicate that you're running beta watchOS when filing bugs, though :-D

**Comment by joetomasone** [comment]
FYI, joined the Testflight but it apparently cannot install the Beta app on the Beta WatchOS.   I filed feedback on it.

**Comment by Kemmey** [comment]
@joetomasone Hmmm, that's new. TestFlight should definitely work on the betas with more betas :-D 

Once installed, though, you might run into a login issue though. I tried replicating yesterday, but was not able to. But people are reporting that on beta 3 the login screen does not show up with the store build. I'm unable to replicate with a beta Xcode build - so might require recompilation to fix - but I can't ship builds built with beta Xcode - so wouldn't make any difference :-(
