### ISSUE TITLE
Background Image not showing up

### ISSUE THREAD

**Issue by acmarmia** [Kemmey/Kemmey-TeslaWatch-Public#31]
I am trying to have the image of my Tesla as a background.  I am using the following configuration “ https://observablehq.com/@slickplaid/model-3-configurator” to generate the following URL "https://static-assets.tesla.com/configurator/compositor?&options=$PPSW,$W38B,$DV2W,$MT302,$IN3PB&view=STUD_ “. I take this URL and paste it on the Image URL of the app after turning on Background image.   The image just does not come up.     

Could you help me?

**Comment by fvanson** [comment]
You are doing simple copy / paste of the text on your screen. It is a tiny bit more elaborate as you can read on my blog post on the app: [https://tm3een.home.blog/2020/06/27/apple-watch-app-for-tesla/]

**Comment by Kemmey** [comment]
Hey, @acmarmia - you can actually skip a lot of the steps :-D 

Just paste in "https://static-assets.tesla.com/v1/compositor/" without the quotes, and enable the add querystring option - then the app will generate the correct options for your active vehicle :-D 

The reason no image shows up with your provided url, is that it doesn't resolve to an actual image - try to tap it in your post - you'll see you get a server error from Tesla.

**Comment by Kemmey** [comment]
Hey @fvanson - nice blog post! :-D 

A few factual errors:

1. You don't have to login with username/password - you can generate token yourself and paste that instead. That is my personal preferred way in all 3rd party Tesla apps. ABRP for instance allows you to do the same. 

2. You can actually use the app as key - in that case you DO need to provide your account password in preferences, though. But then you can unlock, activate keyless drive and set off - all from your watch :-D 

3. As stated above, the background image can be even more simple - just paste in "https://static-assets.tesla.com/v1/compositor/" without the quotes and enable the querystring option - then the app will do the rest :-D

**Comment by acmarmia** [comment]
Kim:


        THANK YOU!! That’s worked it it was a lot simpler.

This app is awesome!


acmarmia

**Comment by Kemmey** [comment]
@fvanson oh, and watchOS 7 clearly have padding issues in swiftui - as did 6.1... it seems impossible to properly control app layout across even dot releases of watchOS with swiftui... :-(

**Comment by fvanson** [comment]
@Kemmey : thank you for the hints and corrections. I have updated both the english and dutch version.
You can find them on:
English -> [https://tm3een.home.blog/2020/06/27/apple-watch-app-for-tesla/](https://tm3een.home.blog/2020/06/27/apple-watch-app-for-tesla/)
Dutch -> [https://tm3enl.home.blog/2020/06/27/apple-watch-app-voor-tesla/](https://tm3enl.home.blog/2020/06/27/apple-watch-app-voor-tesla/)
