### ISSUE TITLE
Car won't sleep

### ISSUE THREAD

**Issue by dapper27** [Kemmey/Kemmey-TeslaWatch-Public#32]
Love the app and its simplicity. The unlock charge port is the killer feature as I don't have a Tesla charger so had to use the phone app before. Unfortunately I've had to uninstall your app as it stopped my model 3 sleeping. I even switched off background update but still found my car wouldn't sleep. After uninstalling last night the car has slept all night so am sure it must be your watch app.

**Comment by Kemmey** [comment]
Hmm, if you turn off background updates, then the only reason the app could have kept your car awake was either if it was charging, and background updates were still active, or if perhaps the app was running in the foreground. As long as the app is running in the foreground, it will keep the car awake, as it will poll every 5 seconds - just like the Tesla iPhone app. 

My car has been asleep all night this night - even with background updates active, as it will only wait 45 seconds for the car to wake up - when the car is in deep sleep, it takes longer than that to wake it up - so I often find the initial data in the morning to be 6-7 hours old...

But I would REALLY like to get to the bottom of this and make sure it's not a bug - would you mind installing the app again and monitor sleep cycles once more - making sure background updates are entirely off - you may even remove the complication, then it will never background update, as there is no reason to do so. And also make sure to not open up either my app or the Tesla app - just keep it installed, logged in, but not opened. Verify that the car sleeps properly. Then start using the app as normal, and then verify if it is kept unnecessarily awake. 

I hope you'd be willing to help me out here, because I can't reproduce your findings with my model 3...

**Comment by Kemmey** [comment]
Oh - and sentry - make sure sentry is off - but I guess you're already aware of that :-D

**Comment by wombat996** [comment]
Same issue with a Model 3. Installed the app, used it, love it. The car wouldn’t sleep, so I turned off background updates and force closed the app. It still wasn’t sleeping, so I left it overnight just to be sure. It stayed awake all night, so I deleted the app. The car promptly went to sleep. I also turned off my iPhone and switched to my android, so maybe the iPhone  had an effect. I’m now going back to the iPhone only to see if the car sleeps. If so, I’ll reinstall the app and let you know what happens. Fingers crossed, because from what I’ve seen, it’s a great app!

**Comment by Kemmey** [comment]
Thanks for helping test this out!

There must be some weird combination of bugs going on - if we can narrow it down so I can reproduce, or you guys can reproduce, then I can ship some debug builds to you two, and see if this can be fixed.

**Comment by wombat996** [comment]
Still having issues with the iPhone. I reinstalled your app, and its working great. I rebooted the Tesla and set the sleep attempts to 20 minutes in TeslaFi. The car is currently sleeping, so I don’t think it has anything to do with your app. I had zero problems with my Android, so maybe its just something between iPhones and 2020.24.6.1. Something else comes up, I’ll let you know. Thanks for the great app and awesome support!

**Comment by samiruk** [comment]
The app is fantastic. Same concern about the car not sleeping. What exactly does “background updates” and “allow wake in background” mean?
I don’t want the app to keep waking the car but it would be nice for the complication to give me the right charge level in the morning after I’ve charged overnight. The Tesla app allows the vehicle to sleep. What setting should I use on the watch?

**Comment by Kemmey** [comment]
@samiruk basically you have two options for now. 

You can disable background updates entirely - then the complication will only update whenever you manually open the app. 

Or you can leave background updates on but disable the allow wake in background option - that will still allow the app to do background updates, but it will not wake the car if it is asleep. That also means that unless you have sentry active, the complication probably won't be up to date. 

I'm working on a new setting that will allow you to set an timespan in which wake will be allowed - so for instance you could allow wake from background only between 6-8 in the morning and have the car sleep all night.

**Comment by samiruk** [comment]
Thanks for clarifying that. Amazing app. Just tweeted Elon about it!

Sent from my iPhone

On 1 Jul 2020, at 20:58, Kim Hansen <notifications@github.com> wrote:

﻿

@samiruk<https://github.com/samiruk> basically you have two options for now.

You can disable background updates entirely - then the complication will only update whenever you manually open the app.

Or you can leave background updates on but disable the allow wake in background option - that will still allow the app to do background updates, but it will not wake the car if it is asleep. That also means that unless you have sentry active, the complication probably won't be up to date.

I'm working on a new setting that will allow you to set an timespan in which wake will be allowed - so for instance you could allow wake from background only between 6-8 in the morning and have the car sleep all night.

**Comment by fvanson** [comment]
I have same problem of car not sleeping.
Turning off Background updates (both settings) completely solved it for me since Sunday evening.
Below proof of this problem from TeslaFi last Sunday morning (so after Saturday midnight).
![Schermafbeelding 2020-06-29 om 12 42 02](https://user-images.githubusercontent.com/67519349/86393645-a1e13600-bc9d-11ea-892c-4f09e3dc59dd.png)

**Comment by Kemmey** [comment]
Hey @fvanson 

Awesome with TeslaFi stats to get to the bottom of this! ❤️

Am I understanding this correctly, that what we are seeing is that with Allow wake in background set to the off position, it is still waking the car every hour and thus the car only sleeps for 40 minutes?

Just to be clear - and please forgive me if this sounds silly, but UI elements can be tricky - did your settings look like 

A: ![image](https://user-images.githubusercontent.com/4688084/86403308-c04f2d80-bcad-11ea-948d-33b22520fe8a.png)

Or 

B: ![image](https://user-images.githubusercontent.com/4688084/86403337-ca712c00-bcad-11ea-8601-725ed42653d6.png)

**Comment by dapper27** [comment]
![Annotation 2020-07-03 063426](https://user-images.githubusercontent.com/44276659/86435239-72f7ae00-bcf7-11ea-9f5c-19f6b992491f.jpg)

Seems to be working again fine (I joined Testflight so I have the latest versions - currently 146 but I see 147 has just landed)

On the diagram above (from Teslamate, which I can thoroughly recommend), the dashed lines represent midnight.

On 26 & 27 June the car would sleep for about 44 minutes at a time and then wake up again. I had 'allow wake in background' switched off.

I uninstalled at about 10pm on 27 June and the car slept all night.

I installed again on 29 June and again the car would sleep for about 40 minutes then wake up again. So I uninstalled about 9am on 30 June and sleeping was back to normal again. (1 July I had sentry mode on during the day hence no sleeping).

I installed again last night and touch wood everything appears to be ok as the car slept all night :-)

One confounding issue is that I rebooted my iPhone and Apple watch a couple of days ago so don't know if that has done anything but it might be something worth trying if you are having sleep problems with the app.

I will keep 'wake in background' off but currently also have 'background update' off but will try with this on and see if it causes any new sleep problems.

**Comment by Kemmey** [comment]
@dapper27 awesome feedback! Thank you!

I think from the collected feed back here, that I'll need to conclude that disabling allow wake simply does not do what it is supposed to. 

I might have to remove the toggle, as it seems just calling the main Tesla api will wake the car, even though it is not supposed to. 

Would the upcoming feature of disabling background updates entirely in certain time intervals be sufficient for your needs, you think? So basically, you'll be able to set "Enable background updates between 7am and 8pm"?

**Comment by dapper27** [comment]
I'm now using the latest testflight beta 1.0.6 (147).
You'll be pleased to know that my car has been asleep for nearly 5 hours now while at work.
Next phase of my test will be to enable background updates but keep 'wake in background' disabled. I'll do that when I wake the car to go home. I will report what happens to sleep overnight after charging is complete.
I have another suggestion / feature request...
The icon you use for the app... would you be able to have a setting for this to be the complication? I'm not overly bothered about having an instant idea of range every time I look at my watch, but the complication is a nice quick way to launch the app when needed, and the icon would just look nicer on the watch face I think (I use the modular face).

**Comment by Kemmey** [comment]
@dapper27 with watchos 7 I'll be able to add multiple complications - I'll add the app icon as one of them :-D

I'm really glad that turning off background updates did keep the car asleep - but I fear that turning off allow wake will not actually keep the car asleep - given other reports in this thread. But it'll be good to have verification.

**Comment by dapper27** [comment]
![Annotation 2020-07-04 143600](https://user-images.githubusercontent.com/44276659/86513649-d7a02f00-be03-11ea-9f4c-24a9a1fdf014.jpg)

Unfortunately car didn't sleep again after enabling 'background updates' in settings. Have switched off again and will report back. No idea why it's doing this, but at least you know that if all updates options are set to off then it doesn't affect the sleep. I don't really need it on anyway for the way I use the app personally. It's good to have a really quick way of opening the car, disconnecting my charging cable and activating keyless drive without having to get my phone out!

**Comment by Kemmey** [comment]
Thank you @dapper27 for sharing your data! 

I'll try to do a thorough read-through of the wake code and see if I can figure this out - if not, then I'll have to remove the feature as it is not working as intended and is misleading...

**Comment by dapper27** [comment]
![Annotation 2020-07-04 222509](https://user-images.githubusercontent.com/44276659/86521176-40f46200-be45-11ea-8ec3-b99558003e35.jpg)

Have left the app on the watch (it's updated to the latest version on testflight). Have disabled background updates. Sleeping again.

**Comment by remy911** [comment]
Hi
I'm from Switzerland and hope my English is good enough.
I test your app now for 2 weeks and I love it, better than Stats and Remote S on the watch. 
I test it in all different kind of ways, with background updates toggles only one on or both off. any possible variation and time to update 15minutes, 30, 1hour etc.
The car is sleeping, if wake up toggle is off. but only for about 1hour and then wake up again. if both toggles are off, car will stay asleep. 
But honestly, that's exactly what i like about the app. it shows me the latest data in the complication and i don't have to run the app.
But there is may be also an other problem with the Tesla application too. Because I changed the password and car was not sleeping until I went in to flight mode with my iphone X. Then Model 3 was sleeping again. When I turn off Flight mode on the phone, car is still sleeping. When I turn on the apple watch and both background toggles are off, car stay sleeping. 
When I turn on watch and only the "wake up" toggle is off, but the other one is on, car will wake up. Very funny behaviour.
hope that helps may be also a little bit.
cheers
Remy

**Comment by Kemmey** [comment]
Thanks @remy911 - that perfectly aligns with the reports above - that the allow wake toggle in the off position, in fact still wakes the car. 

I'll try to see what goes wrong - I mean, if stats, teslamate etc. can manage to monitor sleep without waking the car - I should be able to check if it is awake or not, without waking it. 

So it is definitely a bug on my part.

**Comment by remy911** [comment]
> Thanks @remy911 - that perfectly aligns with the reports above - that the allow wake toggle in the off position, in fact still wakes the car.
> 
> I'll try to see what goes wrong - I mean, if stats, teslamate etc. can manage to monitor sleep without waking the car - I should be able to check if it is awake or not, without waking it.
> 
> So it is definitely a bug on my part.

Hi Kemmey, but auto-update in the complication without starting the app (without tipping on the application) is somthing that stats etc. do not have. 
This for me the major value from your app!

**Comment by Kemmey** [comment]
@remy911 yeah, I'm keepin that for sure! It's the allow wake in background toggle i might have to remove - so either background updates are enabled or they are not. If enabled, they WILL wake. 

But I'll see if I can't fix it.

**Comment by remy911** [comment]
But if the toggle for update (not background if sleeping, the other one) is set to 15minutes, maybe also 30minutes, the car is not sleeping fast or not at all. In my case.

**Comment by Kemmey** [comment]
@remy911 - that is hard to argue - it takes the car up to 20 mins to sleep in my experience - please correct me if I'm wrong, I'm not exactly an authority on this, as I personally don't care - I have Sentry on always :-D

But if you poll every 15 mins, the car will always be kept awake - please keep the polling at approx 1h or more... The app will poll at 15m intervals as long as its charging - so you'll get frequent updates to the complication as long as the car is charging - which is when its most important...

**Comment by Kemmey** [comment]
Oh - but good news everyone! I think I've just found the bug waking up your vehicles!

I did a read-through of the code, and I found a bug where i accidentally called a wrong data method, that will wake the vehicle - in the disallow wake code path. 

I'll have a build up in TestFlight soon - I would REALLY love for you guys to test it out and verify :-D

**Comment by dapper27** [comment]
Ok have updated to the new build and set background updates back on.

Just thought of something that would be useful. You already have a feature where the watch vibrates when a command registers.

Would be useful when the app is first turned on and it's waiting to get a response from the car that it vibrates when it's online.

**Comment by samiruk** [comment]
Vibrating when it’s online is a great idea!
Incidentally how do I update the app once it’s installed on the phone ?

**Comment by dapper27** [comment]
![Annotation 2020-07-06 062148](https://user-images.githubusercontent.com/44276659/86558433-3921e400-bf51-11ea-846d-2147920d3490.jpg)

That must have been a satisfying debugging session.
Sleeping fine now.

**Comment by dapper27** [comment]
You mentioned something about WatchOS 7 letting you have multiple complications...
You can maybe see where this is heading...
If the app detects the car is asleep then have the range with a little zzz next to it maybe.

**Comment by Kemmey** [comment]
@samiruk if you're in the TestFlight beta, you'll have to open the TestFlight app on your phone and update from there

If you want the publicly released version, you can update from the AppStore app on your watch - scroll to bottom in AppStore app, tap account and then updates. 

Just note this update has only been shipped to TestFlight - will probably be a week or two until 1.0.6 ships

**Comment by Kemmey** [comment]
@dapper27 @samiruk i can easily add the bell and vibrate when car is online - however, I don't think I will. 

It IS a good suggestion, however, the APIs Apple give me access to, only allows me to add BOTH a chime and a vibrate. If I could add just a vibrate I would, but the chime has to be there. And currently that is supposed to be associated with success for fail of a vehicle command - and if the success chime sounds without having executed an action, I feel that would be confusing to the users - and might even remove some trust, in that some people would feel the app was executing actions on their vehicles against their wishes.

**Comment by Kemmey** [comment]
@dapper27 that zzz indicator is a really good idea - that won't have to wait for watchOS 7 - I can do that for a few complications right now - the car will never be asleep at the same time as sentry - so all complications supporting the sentry indicator should support the sleep indicator :-D

**Comment by remy911** [comment]
@Kemmey, good news! 
I look forward to the update. I don't even know what TestFlight beta is :-)

**Comment by Kemmey** [comment]
@remy911 TestFlight is the beta platform from Apple, where the beta program is hosted. 

You can join here: https://testflight.apple.com/join/FdzFOLZv

**Comment by remy911** [comment]
thanks Kemmey i'll check it out

**Comment by samiruk** [comment]
I purchased the app from the App Store. I’ve now downloaded the TestFlight app using your link but no ideas how to activate beta versions on the watch. I might just have to wait a week or two until you release the official update. How will we install that update as it’s not on the iPhone ?

**Comment by Kemmey** [comment]
@samiruk hey - go and open the testflight link again from your phone after you've installed the testflight app - it will ask you to open the app and join the beta. When you've joined, you'll have access to install the beta version to the app from within the testflight app. Consider the testflight app as your beta app store :-D All from your phone...

The watch will automatically download updates - so you don't have to do anything, it will do it automatically in due time... You can always go into settings in the app and see what version you have installed. The current app store version is 1.0.5 - the current beta version is 1.0.6 :-D

**Comment by samiruk** [comment]
On another point how about opening the boot ‎as the main icon on the front page? How many people use the frunk over the trunk ?

**Comment by Kemmey** [comment]
@samiruk the main three controls mimic the official Tesla app. At least for model 3 - I see some model s users report that keyless drive is listed instead of frunk...

You can force touch on the main screen, and trunk control is right there :-D that's at least faster than going through the controls list.

**Comment by dapper27** [comment]
From a human factors point of view, best to mimic the Tesla app button layout. The way the brain works on autopilot sometimes, people would get confused if there's a different layout.

**Comment by samiruk** [comment]
Hi please can I have a TestFlight invitation code. It’s asking for that on the iPhone.

**Comment by Kemmey** [comment]
@samiruk open this link on your phone - it should have a start testing button - that should take you directly to the beta in TestFlight. There are no personal codes - it's the same link for anybody and everybody can join:


https://testflight.apple.com/join/FdzFOLZv

**Comment by samiruk** [comment]
Thanks. Appreciated. Managed to get it to work. Seeing a nice 🌙  beside the mileage on the complication. Presumably this means the car is asleep.

Sent from my iPhone

On 7 Jul 2020, at 15:07, Kim Hansen <notifications@github.com> wrote:

﻿

@samiruk<https://github.com/samiruk> open this link on your phone - it should have a start testing button - that should take you directly to the beta in TestFlight. There are no personal codes - it's the same link for anybody and everybody can join:

https://testflight.apple.com/join/FdzFOLZv

**Comment by remy911** [comment]
I also loaded the Beta. still waiting the car sleeping :-)
I'll keep you updated....

**Comment by remy911** [comment]
so from what I've noticed so far.

the car falls asleep again and it stays asleep at least for now.
tomorrow morning i will test if it is not woken up when i turn on the clock. it has always done that until now.

The moon symbol is great!
But it does not appear on my complication until I change it by wiping and then wipe back on my complication, then I see the moon symbol.

**Comment by samiruk** [comment]
Does the circular complication always show percentage...even though my car is set to show miles ? Your other complication in a different watch face shows miles.

**Comment by Kemmey** [comment]
@remy911 the moon symbol - which reflects if the car is asleep - will only be updated if the app has updated in the background and found the car to be asleep. So whenever you actually open the app, it will most likely go away, as the first thing the app does when opened, is wake the car :-D

**Comment by Kemmey** [comment]
@samiruk it really depends on which and where - there's another issue opened here https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/45 that goes into a bit more detail about the complications. 

Long story short - some complications will not fit more than two digits - and then it does not make sense to try to show range - so it will always show percentage...

**Comment by remy911** [comment]
Yes the Car is now sleeping, but there is no moon. Last time there was one. I woke up the car and wait until it is sleeping agein.
Background toggle is on and set to 45 minutes.
Background toggle to allow wake up is off.

**Comment by remy911** [comment]
Car did not wake up this morning, after turning on phone and watch.

**Comment by dapper27** [comment]
> Car did not wake up this morning, after turning on phone and watch.

Sometimes the car will go into a 'deep sleep' - it's not a bug with the app or the watch app. A lot of people on Tesla forums have described this. The only way to wake the car up is to physically open the door and then everything switches on after about 10-15 seconds. Is that the scenario you are describing?

**Comment by remy911** [comment]
> Sometimes the car will go into a 'deep sleep' - it's not a bug with the app or the watch app. A lot of people on Tesla forums have described this. The only way to wake the car up is to physically open the door and then everything switches on after about 10-15 seconds. Is that the scenario you are describing?

no sorry, it is good, that car is not wake up, because befor 1.0.6 the watch did wake up the car every morning.
