### ISSUE TITLE
Tesla is locked but watch assumes it is unlocked

### ISSUE THREAD

**Issue by mac0815** [Kemmey/Kemmey-TeslaWatch-Public#336]
Hi
If i unlock my Tesla with the  Tesla Watch App and if i wait to long the Tesla lockup the Doors again. After this happened, the Teslawatch assumes that the car is still unlocked and you have to lock and unlock the car via the Watch to get the car unlocked again.
Ist That a normal bevavior or just a Sync issue?
Regards Markus

**Comment by Kemmey** [comment]
Hey @mac0815 

That sounds like a sync issue - if you open up the watch app, it should start getting new data straight away - you can verify this by the counter in the header, which indicates age of data - you'll want this counter to be as low as possible, to know you have the most recent data. 

Unfortunately, as long as Tesla doesn't provide push events in their api for state changes, there's no way for the app to update whenever vehicle events happen - the app just have to grab the data periodically instead. 

Cheers, 

Kim

**Comment by mac0815** [comment]
Hi Kim 
Ok, thanks for the Info , i thought that the original Tesla App is based in the API as well, but that seems not the case 
Regards Markus

**Comment by Kemmey** [comment]
@mac0815 No problem :-D 

The official app uses both. When in range, it'll use Bluetooth, else the api.
