### ISSUE TITLE
Watch face

### ISSUE THREAD

**Issue by anister20** [Kemmey/Kemmey-TeslaWatch-Public#337]
It is not clear on how to get a watch face with the tesla car background. I know there are complications that can be added, but I want my tesla car background in the middle of the watch face, as shown in a picture on the app store on iPhone.

**Comment by Kemmey** [comment]
Hey @anister20 

That would be the Infograph Modular watchface available on Apple Watch series 4 and newer. 

For the car to be visible you'll have to enable background image in the app on the watch from settings. 

You can grab a preconfigured watchface here:

https://github.com/Kemmey/Kemmey-TeslaWatch-Public/blob/master/WatchFaces/Infograph%20Modular.watchface?raw=true

Cheers,

Kim

**Comment by anister20** [comment]
Oh, okay. Is there any way to get it for the series 3, or is it simply impossible? If not I understand. 

Thank you!

**Comment by Kemmey** [comment]
No - those are series 4 and up exclusive features. Really boils down to hardware performance - series 4 was a huge step up in processing power and memory, which enabled these more modern faces. My favorite face - Infograph - will show 8 complications! Thats too much fir the s3 to handle unfortunately.

**Comment by anister20** [comment]
Okay that makes sense. Thank you!
