### ISSUE TITLE
Start/Stop charging shortcut failing - Unknown error

### ISSUE THREAD

**Issue by Cakey123445** [Kemmey/Kemmey-TeslaWatch-Public#346]
Hi,

I’m trying to set some timed automation using iOS shortcuts to work around the fact that scheduled charging doesn’t allow you to set an end time and our energy tariff only runs from 00:30-04:30 so the plan was to use scheduled charging start in the Tesla charging settings (in-car) to start at 00:30 and then use a shortcut, automation, time of day to always stop charging at 04:30, regardless of state of charging.

I’ve been trying to test the automation but its always failing with ‘failed for unknown reason’ unless the car is already awake, then it works ok.

Model 3 LR - 2021.4.15.12
App V1.1.6 build 534

Thanks, Kate.

**Comment by Kemmey** [comment]
Hey @Cakey123445 

For each release of iOS, 3rd party apps get less and less background processing time. With iOS 14 we're down to 8 seconds. Usually it takes 40 seconds to wake the car. 

You could try stringing 6 wake commands after each other to try and ensure the vehicle is awake - but that might also fail for too long processing time in the shortcut itself. 

A server based solution to this would be a much more reliable way to do it. Possibly have a look at Teslascope or Charged app if available in your market. 


Cheers,

Kim

**Comment by Kemmey** [comment]
https://getcharged.app

**Comment by Cakey123445** [comment]
Hi Kim,
Thanks for the information on why, easy to understand why its failing. I’m just having a read of https://www.teslaapi.io/ and will probably write something to run as a cron job on the Linux server we have at home. I had a look at charged but it does much more than I need, can’t really justify the monthly cost to myself to be able to just to disable charging and not so interested in geeking out on the large amount of data in there. 
Big thanks for your app by the way, its great being able to pop the frunk and do other things from my watch without having to dig my phone out of my bag.
