### ISSUE TITLE
No Login Screen

### ISSUE THREAD

**Issue by gilz99** [Kemmey/Kemmey-TeslaWatch-Public#35]
I installed and paid for the app on my watch, but it never gave me the Tesla login screen. The app is there as it shows up in my watch's application screen but nothing happens when I click on the app icon.

The only thing that I had not tried was powering down the watch. I just did that and it worked... Thanks for your help

**Comment by Kemmey** [comment]
That's a new one. 

Could you list your watch model and size and the version of watchOS is installed. And for good measure, same for your paired phone. 

I guess you've already tried deleting the app from the watch and installing again from the store directly on the watch? Also, standard Apple debugging procedures: restart phone and watch :-D

**Comment by gilz99** [comment]
Thanks for the tips…. The only one that I had not tried was powering down the watch and restarting. That’s the one that did it. The app is working fine now.
Thanks again,
Gil
