### ISSUE TITLE
Choosing vehicle 

### ISSUE THREAD

**Issue by mistermark31** [Kemmey/Kemmey-TeslaWatch-Public#36]
Purchased the watch app but need it for my other car, how to I choose. Tesla name and email are the same 

Thanks 
Mark

**Comment by Kemmey** [comment]
Hey 

Just tap on the vehicle name in the app and you will enter the vehicle chooser - then choose your other vehicle :-D

**Comment by mistermark31** [comment]
Thanks!

Mark
