### ISSUE TITLE
Doesnt install on apple watch os 6.3

### ISSUE THREAD

**Issue by brodie1227** [Kemmey/Kemmey-TeslaWatch-Public#362]
Installed on iohone. Not on watch. In app store on watch doesnt show as a purchase. Also it does show up to purchase on watch, however does nothing on the “double click to install” please advise. Thank you

**Comment by Kemmey** [comment]
Hey @brodie1227 

Please try to restart both watch and phone and try again. 

If app shows as available for purchase on watch, and you're logged in on watch with same appleid is phone, please try to "purchase" again. You will not be billed a second time, but alerted you can download for free.
