### ISSUE TITLE
App crashes on login

### ISSUE THREAD

**Issue by kda-2020** [Kemmey/Kemmey-TeslaWatch-Public#365]
App crashes on login, have tried to erase app and reinstall whiteout luck

**Comment by Kemmey** [comment]
Hey @kda-2020 

Yeah, sorry about that - known crasher in 1.1.6. Fixed in 1.1.7 which is still being prepared for release. 

You can join the TestFlight to fix immediately:

https://testflight.apple.com/join/FdzFOLZv

Sorry,

Kim

**Comment by kda-2020** [comment]
I have tried, there is a text message service tilstand aktiveret ?

**Comment by Kemmey** [comment]
Yub - so no longer crashing, right?

That message is from the Tesla api - when vehicle is in service mode, normally the api does not respond to user commands. 

If your vehicle is not in service with Tesla, please reach out to Tesla support through their app and ask them to take your vehicle out of service mode.

**Comment by Kemmey** [comment]
The official Tesla app should also reflect service mode. Please let me know if that is not the case! :-D 

Cheers,

Kim

**Comment by kda-2020** [comment]
Tesla service erased the error last night and I can’t see it in the official Tesla app

**Comment by Kemmey** [comment]
Check in Settings, Show debug, Authentication events if there's any recent log out entries. If you see something from "mothership" with vehicle in service, then the api is still reporting vehicle is in service. Nothing I can do my end unfortunately, if Tesla still reports vehicle in service. 

Possibly send me the logs - there's a button to do so in the phone version. 

Cheers,

Kim

**Comment by kda-2020** [comment]
I did put the car in service mode and out again but nothing changes, I have all functions in the org Tesla app
I have sent you an email
