### ISSUE TITLE
Not an issue, but a pretty solid suggestion

### ISSUE THREAD

**Issue by BruhUltimate** [Kemmey/Kemmey-TeslaWatch-Public#39]
I thought about this with the Model III a while back and I'm just not smart enough yet or good enough yet with app development and Swift, but is it possible to make a "drive" mode on the watch app?  Personally, I'd love to have a mode on your watch app to display battery life and speed when the car shifts into drive.  I'm sure this is relatively complicated if even possible (not sure how much access you can get from the car on that level to work in an app, nonetheless if it would work seamlessly or be buggy/delayed response) but if its possible I think its a good solution for Model III in not needing to turn your head to see the speed on the center screen and having no current HUD option.  

I'd be willing to help at all if I can, or even just be able to learn from you since I am really new at coding/developing; especially since I have a lot of free time being unfortunately unemployed during COVID.

**Comment by Kemmey** [comment]
Hey,

That's not a bad suggestion, really!

I most certainly can detect the drive state - so I would be able to change the ui completely to an entirely different view. You're not supposed to fiddle with the app while driving, so it could be a static no-scroll view showing some stats. 

I'm not sure it would be all that more ergonomic to look at your wrist than at the main screen - but it would be a nice coding exercise and interesting feature :-D it would allow me the excuse to use the streaming api :-D 

I'll see what I can come up with. 

Which elements would you like to see? 

SoC, heading, speed?

**Comment by Kemmey** [comment]
These are the available fields from the streaming api: 


["elevation","est_heading","est_lat","est_lng","est_range","heading","odometer","power","range","shift_state","speed","soc"]

**Comment by BruhUltimate** [comment]
Pretty much. Static driving view with speed and battery life. My reasoning
is if you drive *like you’re supposed to according to drivers ed* at 10-2
you can, at least move your watch towards the side of the wrist and it’s
mildly more ergonomic. The one thing that irks me most with the Model III
is that it doesn’t have a gauge cluster to check speed and battery.

**Comment by BruhUltimate** [comment]
When I get back from the gym, I can come up with a little mock up of a
screen that I think would be easy to read at a glance.

**Comment by Kemmey** [comment]
I just threw something together - forgot about SoC - but will be easy to add. 

If you're not running the beta, you can join here: https://testflight.apple.com/join/FdzFOLZv

Build will be up in 30-ish mins :-D

**Comment by Kemmey** [comment]
@BruhUltimate I think I solved this one. With the latest beta going out in half an hour, the driving panel will now use streaming seamlessly for fluent updates as long as there is adequate connectivity. I just tested it out in an area with very spotty connectivity, and streaming kicked in and out appropriately - so for the first time, this feature is actually useable :-D
