### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by anister20** [Kemmey/Kemmey-TeslaWatch-Public#392]
I am not able to login using a token. The app is not giving me that option. I have attached an image of my login screen.
![75CC99DB-A143-4762-B28D-B692EA4C12B8](https://user-images.githubusercontent.com/78944960/129237643-31bee2f2-d153-4fe4-aea9-587bac04516c.png)

**Comment by Kemmey** [comment]
@anister20 I hid the token based login behind the Advanced label, as I had too many support requests from users who did not understand why that feature existed. 

So just tap the Advanced label and paste in your token. 

Cheers, 

Kim

**Comment by anister20** [comment]
Oh I found it thank you!
