### ISSUE TITLE
Beta build 835  no longer shows estimated range

### ISSUE THREAD

**Issue by Cardo1** [Kemmey/Kemmey-TeslaWatch-Public#400]
With version 1.1.9 build 835 I can no longer get the app to display the estimated range. It will only display the rated range.

Is this intentional or a mishap?

**Comment by Kemmey** [comment]
@Cardo1 intentional. 

I'm adding a toggle in settings to override this value from the vehicle - will show either or, everywhere. 

With the addition of status icons on the battery indicator, I'm getting rid of the sub area entirely.

**Comment by Cardo1** [comment]
> @Cardo1 intentional.
> 
> I'm adding a toggle in settings to override this value from the vehicle - will show either or, everywhere.
> 
> With the addition of status icons on the battery indicator, I'm getting rid of the sub area entirely.

Cool, look forward to the new options.
