### ISSUE TITLE
Door/Lock status

### ISSUE THREAD

**Issue by thumbmaster** [Kemmey/Kemmey-TeslaWatch-Public#43]
I'm not sure if this is possible but since the app has an alert for plugging in, how about an alert for when the doors aren't closed/locked after a given period of time of the car being in Park? I know we can check the Tesla app manually for this info but sometimes life gets in the way and kids fail to close the door fully....

**Comment by Kemmey** [comment]
Hey - good suggestion!

Some of the complications will actually already show this with a yellow triangle and exclamation mark - if doors or windows are left open. I still need to query for the sunroof and lock state - those should also warrant a warning. 

It would be trivial to add a notification as well - I'll add that to the list! :-D

**Comment by Kemmey** [comment]
@thumbmaster notifications have now been added to beta version of 1.0.6 :-D

**Comment by thumbmaster** [comment]
Thank you! You're awesome!
