### ISSUE TITLE
Tesla Token/API

### ISSUE THREAD

**Issue by alan409** [Kemmey/Kemmey-TeslaWatch-Public#435]
I'm using the Watch for Tesla on my Apple Watch & iPhone. But I can not figure how to add the token so I can use the watch feature. I have the token on my phone but how do I initialize it for the watch?

**Comment by Kemmey** [comment]
Hey @alan409 

When your phone is successfully logged in, your login should automatically transfer to your watch. However, the Apple Watch connectivity framework is notoriously unstable - rebooting both your watch and your phone usually resets the connection and prompts the Apple frameworks to start their background sync'ing again. 

Cheers, 

Kim

**Comment by alan409** [comment]
Thanks, that worked.
