### ISSUE TITLE
Add option to switch temperature to Celsius

### ISSUE THREAD

**Issue by Dmoffa1** [Kemmey/Kemmey-TeslaWatch-Public#441]
Hi,

Can you add an option to show temperature units in Celsius?

Thank you, great app!

**Comment by Kemmey** [comment]
@Dmoffa1 This is controlled by the settings in your car. App will use same units as are active in vehicle. 

Let me know if that is not the case. 

Cheers,

Kim

**Comment by Dmoffa1** [comment]
Thank you @Kemmey! That is the way it is working, my wife is American and has the car set to Fahrenheit, so was looking for an option to specify in the app itself. Thank you for your response, I’ll keep converting the temperature myself.

**Comment by Kemmey** [comment]
@Dmoffa1 I'll add to my to-do list to add an advanced settings toggle to override vehicle unit choice :-D
