### ISSUE TITLE
No complications showing

### ISSUE THREAD

**Issue by msd101psu** [Kemmey/Kemmey-TeslaWatch-Public#448]
I added the Infograph and modular watch faces, but they have no Tesla complications available.  My watch is old but the OS is up to date.  Watch OS 8.3 watch model A1858.  Thanks!

**Comment by Kemmey** [comment]
Hey Mike,

Do you have the app installed and working properly on your watch?

Did you configure your watch face directly on your watch?

When you pick a complication for a slot, look for Watch for Tesla:


Possibly try restarting your watch?

I've never had the complication picker on the watch not show the
complications properly.

**Comment by msd101psu** [comment]
Rebooting watch fixed it. I should have thought of that.  Thanks!
