### ISSUE TITLE
Complications

### ISSUE THREAD

**Issue by dapper27** [Kemmey/Kemmey-TeslaWatch-Public#45]
Could you give a run down of different complications please! It appears that different areas in different faces have completely different restrictions as to what can be shown (not surprisingly in view of the physical area of the screen covered!).

I tend to use the modular face pretty much exclusively and the complication area in the bottom right corner would only show range digits and nothing else. The large central area shows a ton of info - but only range in miles and not percentage. There is a sentry icon when sentry is switched on and also a message saying 'sentry on' which is probably a bit too much redundancy.

I had a little play with setting up a simple watch face and that showed the range in small characters but with a lightning symbol while charging earlier.

I'm not sure how customisable this is and what face settings I would need to be able to show particular information and icons. You may recall from an earlier thread I had suggested just an icon to take you into the app but I can see now that some of the info being visible at a glance on the watch might be useful.

And I guess this will all change in time with Watch OS 7!!!

Rather than post on here, might be useful on your FAQ with some images.

I'm currently at the 'trial and error stage'  =D

**Comment by Kemmey** [comment]
Hey @dapper27 

You would think the modular complications were the most versatile ones - but they really are not! They can show the circular gauge and two digits - sometimes three if they are small i width. 

But some of the other legacy watch faces will show complications with surprisingly many details - almost as much as the new infograph circular complications, which are really my favorite one for density. 

I've added a few from my complications simulator with various states for your perusal... - these are all from the 1.0.6 beta...

![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 13 54](https://user-images.githubusercontent.com/4688084/86615319-97cc7980-bfb4-11ea-88a1-61a3a1a1d834.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 13 45](https://user-images.githubusercontent.com/4688084/86615326-99963d00-bfb4-11ea-86be-396c2dbaa341.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 13 27](https://user-images.githubusercontent.com/4688084/86615328-9a2ed380-bfb4-11ea-947d-1d24e184d95d.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 13 10](https://user-images.githubusercontent.com/4688084/86615329-9a2ed380-bfb4-11ea-85ff-37a53f2385c7.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 13 02](https://user-images.githubusercontent.com/4688084/86615334-9ac76a00-bfb4-11ea-8cea-2f5e3b06e7e4.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 12 58](https://user-images.githubusercontent.com/4688084/86615336-9ac76a00-bfb4-11ea-85fe-e879058686a1.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 12 31](https://user-images.githubusercontent.com/4688084/86615337-9b600080-bfb4-11ea-8c86-233be1b23576.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 12 09](https://user-images.githubusercontent.com/4688084/86615339-9b600080-bfb4-11ea-8420-f1c53eeb2091.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 12 03](https://user-images.githubusercontent.com/4688084/86615341-9bf89700-bfb4-11ea-83de-ada527295d44.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 12 00](https://user-images.githubusercontent.com/4688084/86615345-9bf89700-bfb4-11ea-8f5b-f4bdc8beeb7c.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 11 46](https://user-images.githubusercontent.com/4688084/86615346-9bf89700-bfb4-11ea-935c-cdbcbca91435.png)
![Simulator Screen Shot - Apple Watch Series 3 - 38mm - 2020-07-06 at 18 11 39](https://user-images.githubusercontent.com/4688084/86615347-9c912d80-bfb4-11ea-9e92-11e7bad26639.png)

**Comment by dapper27** [comment]
Thanks - very comprehensive!
For some reason I only have range - no percentage. On any complication.

**Comment by Kemmey** [comment]
That setting follows your car. Applies to the Tesla app as well. On a few of the larger complications I'll fit in both if sentry is deactivated - but only if car is set to percent.

**Comment by Kemmey** [comment]
Others will only fit percent...

It really comes down to what can fit on the complication...

**Comment by dapper27** [comment]
Ok that makes sense.
Have been deliberating over whether to change to percent. Ultimately it doesn't make any difference over how far the car will go, which is the most important thing!!

**Comment by Kemmey** [comment]
It's personal preference, really. I just don't want the remaining battery capacity to be shown in some arbitrary number - I prefer facts. A percentage is better than actual kWh when you want to see the value at a glance, but I might actually add the proper kWh value as well :-D 

Range is so dependent on weather, load and temper - I understand why the 3 only allows rated range - then at least it will be a static scale that can be learned, and not some idiotic fluctuating arbitrary value... but again, personal preference :-D

**Comment by dapper27** [comment]
I guess ICE cars are often not that much better. Often the fuel gauge will stay at full for quite some time then drop like a stone, and the estimated range would dance around all over the place. Most days I don't even have to worry that I'm going to get down anywhere below 40%. If I'm planning road trips then ABRP is usually pretty bang on the money and the car navigation also pretty accurately estimates the battery % at the destination.

**Comment by Kemmey** [comment]
Yeah - you're right about ice cars :-D I honestly think that is by design for some odd reason - they all seem to do it!

And big thumbs up for ABRP - especially when connected to the vehicle - their learning algorithm is usually bang on...

**Comment by wombat996** [comment]
Love the moon 🌙 for sleeping! Thanks for the test flight info as well. I’ll try to help if anything comes up.

**Comment by remy911** [comment]
with 1.0.6 build 174, on the "Infograph Modular" it is not updating automatically moon etc. on the "Infograph" it seams to work. I'm still testing....

**Comment by remy911** [comment]
o.k again me. had an SW update on the car. Car is now sleeping. 
moon symbol did not show up automatically on both complications. i had to swip back and forth and then the moon symbol showed up. it seems that an automatic update does not work.
