### ISSUE TITLE
Family Sharing

### ISSUE THREAD

**Issue by beechcottage** [Kemmey/Kemmey-TeslaWatch-Public#46]
I see this was also raised in another App Review...
App says it supports Family Sharing but App Store still wants to charge again on a (correctly setup) family member with App purchases shared. Please advise

**Comment by Kemmey** [comment]
Hey!

The app is marked as supporting family sharing - but it is not something I have control over, except allowing it. 

Apple takes a 30% cut of all proceeds for their part in maintaining the infrastructure. I'm not sure they live up to their end of that bargain. 

Please contact AppStore support and have them fix their infrastructure! 

I'm sorry I can't be of more help - but the AppStore infrastructure is completely outside of my control.

**Comment by beechcottage** [comment]
Hi Kim,

 

Understood. No problem.

 

Regards,

 

Tony

tony@beechcottage.co.uk
