### ISSUE TITLE
If no name is assigned to vehicle, a random number is shown in main app and vehicle chooser instead of model name

### ISSUE THREAD

**Issue by Kemmey** [Kemmey/Kemmey-TeslaWatch-Public#47]

**Comment by Pravoslav-ava** [comment]
These numbers are the last five digits of your WIN car.

**Comment by Kemmey** [comment]
@Pravoslav-ava thanks! But you've not specifically set your car name to that number, right? 

I propose to do - in that case - like the Tesla app does - to show the model name instead.

**Comment by Pravoslav-ava** [comment]
Those numbers don't bother me. If someone doesn't want numbers, they can create "MODEL 3", but then it also appears on the left of the car display.
If it could be set to appear on the watch, I would welcome it.
