### ISSUE TITLE
Apple Watch series 2

### ISSUE THREAD

**Issue by jrvulcan** [Kemmey/Kemmey-TeslaWatch-Public#471]
Purchased and it worked great, now it doesn't work anymore.  The app now says it requires 7.2, but series 2 won't go above 6.3.  Disappointed....

**Comment by AbboMG** [comment]
Likewise I have Series2 which whilst old is working perfectly. Why is the phone version not being linked as I want to purchase this app Mr Developer

**Comment by Kemmey** [comment]
@jrvulcan @AbboMG 

I'm sorry - but apple discontinued software updates for the apple watch series 2 - if Apple doesn't supply software updates any longer, there's no way I can justify holding back development of the app for everyone else. 

Please take this out on Apple - not the devs - we were not the ones who discontinued support.

**Comment by jrvulcan** [comment]
What a load of crock
    On Tuesday, May 17, 2022, 01:54:59 PM CDT, Kim Hansen ***@***.***> wrote:  
 
 


Closed #471.
