### ISSUE TITLE
Get Vehicle State Is Charger Connected issue

### ISSUE THREAD

**Issue by HenryGelderbloem** [Kemmey/Kemmey-TeslaWatch-Public#476]
I've been trying to create a shortcut that will ping me a notification if I need to charge my Tesla. Currently I have it to notify me every day regardless of whether or not the car is plugged in or not. 

So trying to make it a little smarter by only notifying me if the car isn't plugged in I tried to use the Get Vehicle State action and putting the Is Charger Connected into a variable. Then trying to use an if statement to only continue to notify me if Is Charger Connected is No however, when attempting to test this condition it only gives me two options, has any value or does not have any value.

This makes outputting Is Charger Connected pointless as we cannot do anything with the output. Can it be updated so that the other tests such as contains or is are also available?

**Comment by HenryGelderbloem** [comment]
Looks like the latest update has fixed the above but there is another issue. 

The condition only allows for numbers not text so you still cannot use an if statement to check if the charger is connected. 



![image](https://user-images.githubusercontent.com/23199752/178149307-8552d339-5f77-4fde-ae9a-23b15c1e5d3f.png)

**Comment by Kemmey** [comment]
Its a Boolean value. True / false is represented by 1 / 0

![image](https://user-images.githubusercontent.com/4688084/178149546-cbfbe2b6-1c29-4bab-b75b-0286aa833de7.png)

**Comment by HenryGelderbloem** [comment]
Looks like that works as expected. Thanks @Kemmey
