### ISSUE TITLE
Frunk & Trunk Parked & Locked

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Kemmey/Kemmey-TeslaWatch-Public#483]
Does opening the Frunk/Trunk first check if the vehicle is in park and unlocked?

If not could these be options? Check if in park
Check if in park & locked

If you can give us access to Tesla states through shortcuts then we could write our own shortcuts.

**Comment by Kemmey** [comment]
All state info is already exposed through Siri Shortcuts intents - so you can write any custom shortcuts actions you please :-D

Vehicle will not allow popping the trunks while driving - so this gate is delegated to car. I could see many instances where these would be handy to be able to perform in both locked state and in drive state, but not moving.

**Comment by TeslaOwnerTips** [comment]
Do I have to run wake up before a command?

**Comment by TeslaOwnerTips** [comment]
Could you please implement 

/api/1/vehicles/{id}/vehicle_data

Return a dictionary 
Maybe 
Get Vehicle Data
