### ISSUE TITLE
[Feature Request] Basic summon forward/backwards

### ISSUE THREAD

**Issue by d3vzer0** [Kemmey/Kemmey-TeslaWatch-Public#49]
First of all, kudos for making this app! I was interested in buying the physical key fob (for the frunk/chargeport control) but using the Apple Watch app is such a more elegant (and cheaper) solution 👍 

Would it be possible to implement the 'basic' summon as well? ie. controlling the car to go forward or backward? I'm currently in the process of buying FSD and it would be amazing to control the car using the watch as well.

**Comment by Kemmey** [comment]
Thanks for the kind words! :-D

I must admit, I've been getting a lot of requests for it. 

And other apps have already done it. 

I'm not sure that it is still possible to do, as it now require bluetooth range for it to work? At least in Europe.

In any case, I don't have FSD - and live in europe where it's severely gimped anyway - so I'm not able to test summon. 

Also - as the summon feature is barely functional as it is from what I hear - I don't think it would be a good idea from a support perspective - my app would get all the blame for the feature not working - plus I might risk being liable for accidents. 

I'm sorry - but it's just not going to happen. 

Give Remote S a try if you need summon: https://apps.apple.com/us/app/remote-for-tesla/id991623777 

It's a REALLY great app - it's what I used before I made my own :-D

**Comment by Pravoslav-ava** [comment]
The basic Summon back and forth is functional and easy to use in the EU with FSD, and it would be good to put it on your watch.

**Comment by Kemmey** [comment]
Hmmm - I've seen a lot of posts on reddit lately from people complaining that it doesn't work since the car requires short range Bluetooth connection to the phone? And if true, I couldn't even do it from the watch...

But tell you what - if some oil sheikh wants to buy me FSD, I'll do my best to implement :-D

**Comment by Pravoslav-ava** [comment]
You have good ideas, so you made a great application.

**Comment by nachtbraker** [comment]
I have summon on my Model S AP2.5. It is totally useless here in the Netherlands:
- Can drive only a few meters. It takes longer for summon to start up than to just walk to the car and get in.
- Sometimes it is useful to get out of a tight parking space. But last time I needed that, I was in an underground parking garage with no mobile signal. -> refused to work.

**Comment by d3vzer0** [comment]
@Kemmey Understandable that this won't be implemented :) No idea what the requirements are in regards to bluetooth connectivity when activating the 'simple' summon variant (ie. forward and backward only), I only know that the smart summon has an EU-range limitation where you need to be +- 5 meters away from the car. Not sure if this is measured by checking Bluetooth connectivity or using the phone's GPS location

**Comment by Kemmey** [comment]
Basic summon is now in TestFlight. But will most likely not ship to appstore. But give it a try and let me know what you think.

**Comment by Pravoslav-ava** [comment]
OK !

**Comment by d3vzer0** [comment]
@Kemmey Very interested in testing this btw :) Is the TestFlight invite link public?

**Comment by Kemmey** [comment]
@d3vzer0 Absolutely - anyone can join using the link :-D

**Comment by d3vzer0** [comment]
@Kemmey Thanks, running the beta now :D I do see the new pages to swipe between the main menu and settings but don't see a new icon to start summon. Should I change anything to activate the feature? :)

**Comment by Kemmey** [comment]
@d3vzer0 I had to remove the feature as I shipped the 1.0.7 branch to the store. You can go back and grab the old build in TestFlight - navigate to previous build and find build 1.0.7 289 - that build still has the summon code active.

I did some testing with a guy in Norway, and it basically didn't work. Though it did work on my car, for the 48hrs I had EAP...

I'll comment it back in for 1.0.8 to continue testing - but the last known state was basically, that it worked on my car, but not for anybody else...

**Comment by d3vzer0** [comment]
@Kemmey Just tested it out and it works 😱🥳
