### ISSUE TITLE
Reset iWatch

### ISSUE THREAD

**Issue by nothebrightest** [Kemmey/Kemmey-TeslaWatch-Public#5]
I reset my watch. I can’t get the Tesla for iWatch back. In the App Store it doesn’t let me click on anything (only says “purchased”) and the app is no where to be found. This is likely a issue I need to address with Apple but I realized that as I was typing so I will continue with this avenue. App is great btw. I had the Tesla Remote app forever but it would never succeed in waking my M3. Yours worked like a charm, and quick!

**Comment by Kemmey** [comment]
Hey,

Thanks for purchasing the app - I'm really happy you like it!

Could you verify two things - that after reset, that you are still logged in to the App Store on your watch? And that you try installing the app directly on your watch in the watch AppStore app? See the FAQ on that.

**Comment by balyesh** [comment]
it seems that for iwatch only apps you need to use the app store on the iwatch to re-download not on your phones app store.

**Comment by ludowan** [comment]
Bonjour, application téléchargée mais ne s’installe pas sur mon Apple Watch. Malgré un reboot de celle-ci. Que faire ?

**Comment by Kemmey** [comment]
@ludowan please try to install it from the app store app directly on the watch - search for the app in the apple watch app store app and then you can download it. 

Unfortunately that happens a lot, but it is completely out of my control - it's a bug in the watch<->phone operating system integration

**Comment by ludowan** [comment]
Impossible de télécharger à nouveau l’application. Celle-ci n’apparaît pas sur ma montre malgré un effacement complet 😥

**Comment by Kemmey** [comment]
@ludowan Have you tried doit it from the watch? Can you attach screenshots?

![image](https://user-images.githubusercontent.com/4688084/87545733-c0392f80-c6a8-11ea-8a14-2d35521aa1bd.jpeg)

![image](https://user-images.githubusercontent.com/4688084/87545750-c6c7a700-c6a8-11ea-88f3-0c551f5205a9.jpeg)

![image](https://user-images.githubusercontent.com/4688084/87545755-ca5b2e00-c6a8-11ea-8ccf-ef073c84c245.jpeg)

![image](https://user-images.githubusercontent.com/4688084/87545764-ce874b80-c6a8-11ea-963d-d00c2f593a3e.jpeg)

![image](https://user-images.githubusercontent.com/4688084/87545779-d2b36900-c6a8-11ea-8b00-d72d119cf060.jpeg)

![image](https://user-images.githubusercontent.com/4688084/87545802-d810b380-c6a8-11ea-86fd-f4bda3b27451.jpeg)

**Comment by ludowan** [comment]
C’est bon ça marche. Merci à vous !!!

Envoyé de mon iPhone

**Comment by poweroftwo2** [comment]
So helpful, thanks!
