### ISSUE TITLE
Sleep indicator not updating in background

### ISSUE THREAD

**Issue by Kemmey** [Kemmey/Kemmey-TeslaWatch-Public#50]
o.k again me. had an SW update on the car. Car is now sleeping. 
moon symbol did not show up automatically on both complications. i had to swip back and forth and then the moon symbol showed up. it seems that an automatic update does not work.

_Originally posted by @remy911 in https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/45#issuecomment-655454680_

**Comment by remy911** [comment]
I test now with build 178....

**Comment by remy911** [comment]
unfortunately still no automatic appearance of the moon symbol.
I have to wipe back and forth between the complications. Am I the only one with this phenomenon?

**Comment by remy911** [comment]
with build 179, still the same.
Car sleeps after 15minutes. background update set to 30minutes. car sleeps for 1h. no moon symbol. I have to wipe back and forth, then it appears.

**Comment by remy911** [comment]
Build 180, moon symbol has disappeared.

**Comment by remy911** [comment]
it is visible again after reset the watch

**Comment by remy911** [comment]
something new: car loading and is also displayed in the complication.  then loading is done.  car sleeps and after I wipe back and forth the complication shows me the charging symbol and the moon at the same time.  additionally how long it takes to load.

**Comment by remy911** [comment]
nobody else an input to it?

**Comment by Kemmey** [comment]
Hey @remy911 

I'm on an extended weekend stay, and have not worked on the app this weekend :-D 

I'll let you know when I've managed to look into the sleep indicator feature and will have something for you to test. 

Until then, please accept that it is broken and that I will look into it before 1.0.6 ships to the AppStore :-D

**Comment by remy911** [comment]
Hey Kemmey, thank you. 
but I was actually thinking more about whether others have this phenomenon or just me.

**Comment by remy911** [comment]
still the same with 187

**Comment by Kemmey** [comment]
@remy911 I've made some changes to the reloading of the complications - please give the next build going out in about half an hour a try...

**Comment by remy911** [comment]
it seems to be bether now...I'm still testing

**Comment by remy911** [comment]
It is working now! Thanks. When is the 1.0.6 in the shop  for download ready?

**Comment by Kemmey** [comment]
@remy911 awesome!

I have three issues I'd like to include with the 1.0.6 release - I need to trim and adapt the notification layout and make the notification interactive, I need to get the legwork done for a sign-in helper app so I can ship that later and then I need to get the latest translation keys for all languages. 

So at least two more weeks, I guess :-D

**Comment by remy911** [comment]
o.k I can still use the testflight....
