### ISSUE TITLE
UK App Store issues 

### ISSUE THREAD

**Issue by Niloc0791** [Kemmey/Kemmey-TeslaWatch-Public#501]
Hi,

you were advertising 75% discount on App over the weekend, to coincide with iOS 16 launch. but on checkout on UK App Store this did not apply and it wanted to charge me full price?

what was the issue?

**Comment by Kemmey** [comment]
Most likely that it is no longer "the weekend", it now being Monday? The price is not only shown at checkout - it is literally written on the purchase button. 

But in any case, the App Store is an Apple service, and sales are between end customer and Apple - so please contact Apples support team for any store inquiries, as devs have absolutely zero control over store transactions.

**Comment by Niloc0791** [comment]
Sigh., really helpful stating no longer the weekend….Issue occurred at weekend, just didn’t report it until today. 
Never mind will contact App Store

**Comment by Kemmey** [comment]
Fair enough, sorry for the sarcasm. But you won't believe how many have asked for exceptions because they JUST missed the sale.

**Comment by Niloc0791** [comment]
No worries,  I use  “App sliced”  to track prices, and could see reduced price on US store, but had to buy UK. If I get a constructive response from App Store will pass it on… you never know there might have been an issue!
