### ISSUE TITLE
french version ?

### ISSUE THREAD

**Issue by ze-frog** [Kemmey/Kemmey-TeslaWatch-Public#503]
bonjour from france,
...

**Comment by Kemmey** [comment]
The app should be fully translated to French. Do you have your watch set to French language?

**Comment by ze-frog** [comment]
yeaph you're right, sorry for troubles

**Comment by Kemmey** [comment]
No problem! If you have any changes to the translations, they are here:

https://github.com/Kemmey/Kemmey-TeslaWatch-Public/blob/master/Localizations/fr.lproj/Localizable.strings

A lot of the later ones are sadly machine translated, so some things certainly are not correctly translated.
