### ISSUE TITLE
App not showing in list of complications

### ISSUE THREAD

**Issue by zuluflight11** [Kemmey/Kemmey-TeslaWatch-Public#54]
I would like to add the app to top left of watch face but app does not show in list of complications, just in list of watch apps. I restarted iPhone but it did not change. How do I had shortcut to upper left of watch screen?

**Comment by Kemmey** [comment]
Try to do it directly from the watch - force press on the watch face and choose customize - sometimes the complications take a while to sync to the iPhone watch app
