### ISSUE TITLE
Display when charging

### ISSUE THREAD

**Issue by samiruk** [Kemmey/Kemmey-TeslaWatch-Public#55]
When charging you have to scroll right down to discover that the car is actually charging. Perhaps a more prominent notification would be better to show state of charge and time remaining. Perhaps like the warning you give when the door is open etc ?

**Comment by Kemmey** [comment]
Good point - I'll start by adding the lightning emoji to the battery percentage / range when charging.

**Comment by Kemmey** [comment]
That has actually annoyed me as well :-D
