### ISSUE TITLE
HomeLink

### ISSUE THREAD

**Issue by TeslaRen** [Kemmey/Kemmey-TeslaWatch-Public#56]
Hello, I don't see the HomeLink feature on my WatchforTesla app. I have FSD yet it is still unavailable. Any thoughts?

**Comment by Kemmey** [comment]
Hey,

Are you running the beta version? If not, then please join the TestFlight beta at https://testflight.apple.com/join/FdzFOLZv and check the debug output for Homelink under settings. 

The button will only show up if the car reports primary Homelink device is within reach. 

Do you see the Homelink button in the Tesla iPhone app, and does it work as intended?

**Comment by Kemmey** [comment]
![image](https://user-images.githubusercontent.com/4688084/87345641-a684d480-c550-11ea-8c3b-a905e56f61aa.png)

If it shows false for Homelink nearby, then the car reports Homelink as out of range, and the app therefore hides the button.

**Comment by TeslaRen** [comment]
I finally figured it out and now the Homelink works on my phone and watch. 
I found the fix, below:

“ On your car's screen go into settings, then Autopilot and then Summon Settings (must be in park for this to be accessible) and towards the bottom you want to enable the option to open garage doors upon summon. If you have more than one Homelink door programmed you will also want to specify which door to toggle.”

**Comment by Kemmey** [comment]
Ok - so - wow - there are a lot of requirements to get Homelink working. Not only do you have to retrofit the transceiver, but you also have to have FSD and the you must enable automatic toggle by the car. Hmmm...

Thank you SO much for sharing your solution! I'm sure this will help a lot of people, because that was definitely not obvious!

**Comment by TeslaRen** [comment]
You’re welcome. I loved the watch app before getting Homelink to work but now I’m overjoyed. 

It does not makes sense that Homelink only works with FSD. Seems like it’s easy to program but Tesla like the extra money!!

**Comment by TeslaRen** [comment]
Good afternoon,

 

Can you assist me with the Tesla app. It appears to not be connecting to my Tesla at all. Should I uninstall and reinstall?

 

Thanks so much,

Lauren

**Comment by Kemmey** [comment]
Hey,

Best bet is to verify vehicle is online. Check vehicle is either on WiFi or mobile data as seen directly in the vehicle. 

Possibly restart the infotainment system by holding both wheel buttons until the screen turns black.

**Comment by TeslaRen** [comment]
The app works on my phone without issue.  Should I still restart the i infotainment system anyway?

Thanks for your prompt response.

**Comment by Kemmey** [comment]
No, not if the iOS Tesla app works fine. 

Try to log out on the watch and log back in. 

You might try this login assist app to help logging back in:

https://testflight.apple.com/join/iCBIS6lc

**Comment by TeslaRen** [comment]
The app does not allow me to use iPhone keyboard to log-in. 

 

Sorry for the questions.

**Comment by Kemmey** [comment]
The continuity keyboard is not controlled by the app. It is controlled by the watchOS / iOS system softwares. 

Please verify do not disturb is not active - check Notification Center for the keyboard notification. 

If no notification is received from the watch, verify Handoff is enabled:

https://github.­com/Kem­mey/Kem­mey-Tes­la­Watch-Pub­lic/is­sues/23#is­suecom­ment-680976110

**Comment by TeslaRen** [comment]
All is well in the world again! For some strange reason, once I took it off WiFi I was able to reconnect and was able to use handoff to renter password. 

I really love this app. Hopefully one day we can use voice commands!

Thanks so much...Lauren

**Comment by Kemmey** [comment]
If you join the beta, I've recently added basic Siri support


https://testflight.apple.com/join/FdzFOLZv

**Comment by TeslaRen** [comment]
Whoohoo!!!!  I will do that.

**Comment by TeslaRen** [comment]
Hello there, 

My watch won’t start my Y anymore. I did the upgrade and shut everything down.  There is not place to accept password after I enter it on the watch.

**Comment by TeslaRen** [comment]
Also, how do I know if I’m on the beta version?

**Comment by TeslaRen** [comment]
Sorry for all of the messages. The remote starts works again.  Can you help with the beta version ?
