### ISSUE TITLE
How to add the graphic corner complication to your watch face 

### ISSUE THREAD

**Issue by sallyfortin** [Kemmey/Kemmey-TeslaWatch-Public#58]
I would like to know how to add the corner complications to my watch

I bought the apps specially for this features and it doesn’t work on my watch model a2093
Ios version 6.2.6

**Comment by Kemmey** [comment]
Hey @sallyfortin 

That would be a series 5 gps watch - which certainly can use the new modular watch faces. 

So you need to choose a modular watch face that has corner complications - like the Infograph watch face. Press hard on your watch face and then tap customize, swipe to complications and tap the corner you want to place the complication in and scroll the crown until you see "watch for tesla".

**Comment by Kemmey** [comment]
![image](https://user-images.githubusercontent.com/4688084/87426138-10e45600-c5df-11ea-9e64-dc99e45c4b54.png)
![image](https://user-images.githubusercontent.com/4688084/87426154-15107380-c5df-11ea-9e9f-584850689320.png)

**Comment by sallyfortin** [comment]
Good

And how to add that sentry is on ?

Le 14 juil. 2020 à 8:34 AM, Kim Hansen <notifications@github.com> a écrit :

﻿

[image]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4688084%2F87426138-10e45600-c5df-11ea-9e64-dc99e45c4b54.png&data=02%7C01%7C%7C66f615c393154279a2e508d827f241d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637303268719177349&sdata=XRhTPx7vvuYlBbiFiR1f3bwlooWIxDqVVGE8CfdYlL4%3D&reserved=0>
[image]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4688084%2F87426154-15107380-c5df-11ea-9e9f-584850689320.png&data=02%7C01%7C%7C66f615c393154279a2e508d827f241d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637303268719182338&sdata=%2BivT3EygEbj5ofjthGsLZWsCFH2%2FxCSTT43qeMLJ1N4%3D&reserved=0>

**Comment by Kemmey** [comment]
That is automatic. If sentry is on, there will be a red dot. 

Please note that the complication only updates in the background once an hour by default - this can be controlled from within the settings - but I recommend using default settings.

**Comment by sallyfortin** [comment]
Cool

I like it

Fred

Le 14 juil. 2020 à 8:59 AM, Kim Hansen <notifications@github.com> a écrit :

﻿

That is automatic. If sentry is on, there will be a red dot.

Please note that the complication only updates in the background once an hour by default - this can be controlled from within the settings - but I recommend using default settings.

**Comment by sallyfortin** [comment]
Good
It work

Le 14 juil. 2020 à 8:59 AM, Kim Hansen <notifications@github.com> a écrit :

﻿

That is automatic. If sentry is on, there will be a red dot.

Please note that the complication only updates in the background once an hour by default - this can be controlled from within the settings - but I recommend using default settings.
