### ISSUE TITLE
Watch complication shows watch battery not Tesla

### ISSUE THREAD

**Issue by pjfranks1509** [Kemmey/Kemmey-TeslaWatch-Public#60]
Watch complication shows watch battery not Tesla Battery.  Watch is version 6.2.8

**Comment by pjfranks1509** [comment]
Sorry. My watch battery and Tesla battery are at the same percentage.  It threw me off a little.  Can I have the Tesla miles remaining show on the watch complication not percentage?

**Comment by Kemmey** [comment]
@pjfranks1509 Sure - the app follows prefs in your car. Change the value in your car, and the app updates pretty much live :-D

**Comment by pjfranks1509** [comment]
Thanks for the reply.  My car is set to miles,
![image](https://user-images.githubusercontent.com/68518860/87940585-757c3680-ca5f-11ea-9caa-feb7e6915647.png)
 not a percentage.  My watch face is the Infograph Modular. The bottom left is my percentage of the car's battery.  If I tap it, it shows the miles, not percentage.  I wonder if it’s the watch face that I am using? 
 
Next question: I have to tap on the percentage to update it also to get the reminder to charge.  Is there a setting that makes it update faster? IF so what are your recommendations?
![image](https://user-images.githubusercontent.com/68518860/87940537-5c738580-ca5f-11ea-91bd-8125594fced1.png)

**Comment by Kemmey** [comment]
@pjfranks1509 Oh - yeah - the Infograph circular complication is confusingly limited. All I can fit is two digits - so it will always fallback to percent as range just won't fit. Really silly, as they're much larger than the old smaller modular circular, which in some cases will fit range...

**Comment by pjfranks1509** [comment]
Is there a setting that makes the app update faster? IF so what are your recommendations?

**Comment by Kemmey** [comment]
You can change the background update interval from settings. Default is every hour - or every 15 minutes if charging. 

I recommend the defaults - both to save battery on your watch but also to allow your vehicle to sleep. 

WatchOS only allows an app about 50 background updates per 24 hours - so keep that in mind if you adjust the interval up. You could go up to every 30 min and stay within budget - or you could estimate that you don't wear your watch for more than 12 hours a day and go up to every 15 mins.
