### ISSUE TITLE
Home Like was but now is not showing in the list of commands

### ISSUE THREAD

**Issue by CmdrMGL** [Kemmey/Kemmey-TeslaWatch-Public#61]
Apple Watch 4 running iOS 6.2.8
Late 2016 Model S with home link enabled and working 
This was 1 of the big reasons I got your app.
The rest seem to be working except for window vent and close
This is A SWEET app and am looking for it to become Indispensable 
Thanks 
Mike Lebak

**Comment by Kemmey** [comment]
hey @CmdrMGL 

HomeLink will only show if the car reports the primary homelink device to be reachable. 

Verify that you can trigger homelink with the tesla app on iphone, and allow the watch app to refresh, then try again. 

Window venting/closing seems to not be possible with certain model S's - I have no clue as to why. From the reports I'm getting, it's not possible with the iphone app either - that will only offer sunroof control. Which is implemented in current beta.

**Comment by CmdrMGL** [comment]
Hey
Thanks a lot for the VERY quick response.
I’ll have to get the opener manual out.
Doesn’t work from the Tesla app. But it opens and closes from inside the
car and car ids it as a home link device
Thanks for your time and effort 😁

**Comment by Kemmey** [comment]
@CmdrMGL btw, check this comment to see if that applies to you: https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/56#issuecomment-658166513

**Comment by CmdrMGL** [comment]
BOOOM
#56 indeed does apply to me !!!
Works like it should (who the hell would look in FSD)
Tell TeslaRen thanks and good work !
Mike Lebak
