### ISSUE TITLE
Sentry Mode alerts on watch

### ISSUE THREAD

**Issue by pkt1233** [Kemmey/Kemmey-TeslaWatch-Public#62]
I'd love to get an alert on my apple watch whenever a Sentry Mode event occurs

**Comment by Kemmey** [comment]
@pkt1233 Yeah - I would love that as well. Unfortunately sentry events are not available through the api currently, though I heard some rumors that there's placeholder code to support notifications for events. Fingers crossed the official app ads support for it with a video payload like HomeKit secure video :-D

**Comment by pkt1233** [comment]
Thanks!
