### ISSUE TITLE
Speed on watch 

### ISSUE THREAD

**Issue by samiruk** [Kemmey/Kemmey-TeslaWatch-Public#64]
I know it’s just a novelty thing but just to report that the speed shown on the watch does not match the car speed even allowing for a decent lag time.

**Comment by Kemmey** [comment]
Interesting! Is the car set to miles or kilometers? And which model? My model 3 matches 1:1 in kilometers.

**Comment by samiruk** [comment]
The car is set to miles. It’s a model 3 LR AWD.

**Comment by Kemmey** [comment]
That is really weird - the API is miles native, so no conversion is going on - I'm literally just dumping the api value to screen in that case. 

How much off would you say it is? And is it using the streaming api - you can detect this by the data age indicator in the app title-bar - if it's using polling it will count up to 5-10 seconds between updates - if it's using streaming it should stay at 0 seconds as data flows in...

**Comment by samiruk** [comment]
It was consistently about four or five miles off.  It must be polling but I will check and report back.

**Comment by DJBARTUK** [comment]
How do you see speed? I can’t see how to activate the watch face? Is their a full user guide?

**Comment by Kemmey** [comment]
@DJBARTUK when you put the car in drive you'll see a small banner showing your current gear, speed and heading. If you tap that banner, it'll show in full screen - and also show your current motor power output. 

I've not written a complete manual, as it's a really simple app - basically, try tapping everything and see what happens :-D I'll eventually get around to taking screenshots and do some arrows and explain what each thing does - but I'm prioritizing my time currently on actually improving the app - and as I'm doing so, the screens change all the time - so if I had to do full documentation, I could not improve the app as much as I'd like. I'm just one guy, doing this app in my spare time when my kid's asleep :-D

**Comment by DJBARTUK** [comment]
![54B98319-4989-437F-84FF-A2726E0A6874](https://user-images.githubusercontent.com/68914618/89047929-064bef80-d347-11ea-928e-c7f6da41e16c.jpeg)

Seems to look the same in all areas when driving

**Comment by Kemmey** [comment]
Ah - yes, you need to open the app. The complication will not be able to show speed. It can only update 50 times per 24 hours, as dictated by Apple to conserve power on the watch.

**Comment by Kemmey** [comment]
![image](https://user-images.githubusercontent.com/4688084/89048926-c38f1500-d350-11ea-836e-e5f30d121b88.png)

![image](https://user-images.githubusercontent.com/4688084/89048996-d73a7b80-d350-11ea-9c67-238a440d8bb5.png)

**Comment by Kemmey** [comment]
Tap the small bar below the battery to enter full screen. Tap the small X button to exit full screen

**Comment by DJBARTUK** [comment]
Tried that but no change I’ve set the interval to 15 mins

**Comment by DJBARTUK** [comment]
![D56268E4-2773-46CA-947E-176BB378798D](https://user-images.githubusercontent.com/68914618/89050956-63e23b00-d34b-11ea-905d-55f1e144880a.jpeg)

Can’t see it

**Comment by Kemmey** [comment]
Oh wait! I thought you were on the beta? The driving view has not shipped to the store yet. 

You can join here: https://testflight.apple.com/join/FdzFOLZv
