### ISSUE TITLE
Doesn’t show lock status at complications

### ISSUE THREAD

**Issue by nicholas2471** [Kemmey/Kemmey-TeslaWatch-Public#67]
Hi,
looks like it only shows the battery level and sentry mode. Shouldn’t be showing the lock status which probably the most important info?
Thanks

**Comment by Kemmey** [comment]
Hey @nicholas2471 - the complication by default only updates every hour in the background, so an indication of the lock state would not be very reliable. 

In the upcoming 1.0.6 release there will be a feature you'll probably like, if lock state is the most important info to you: open features reminder - will show a warning ⚠️ icon on the complication if any features are open - doors, windows, sunroof or indeed, if car is unlocked. It will also optionally send a push notification alerting you to this fact.

**Comment by Kemmey** [comment]
You can join the beta to test this out now: https://testflight.apple.com/join/FdzFOLZv
