### ISSUE TITLE
Can't type in username or password

### ISSUE THREAD

**Issue by frjps** [Kemmey/Kemmey-TeslaWatch-Public#69]
When I click on one of these fields, I only see the Cancel button, not a keyboard. How am I suppose to enter the information????

**Comment by Kemmey** [comment]
You should have a few options available - dictate, scribble and continuity keyboard:

![image](https://user-images.githubusercontent.com/4688084/88476579-ad8ce900-cf39-11ea-974d-076b9ecec1a0.png)

![image](https://user-images.githubusercontent.com/4688084/88476581-b382ca00-cf39-11ea-8fe0-1969e9278be0.png)

![image](https://user-images.githubusercontent.com/4688084/88476583-b7aee780-cf39-11ea-9aaf-a9fb6fe0e615.png)

**Comment by Kemmey** [comment]
If none of those are available, try to restart your watch and phone and ensure the watch is connected to your phone via bluetooth.

**Comment by frjps** [comment]
I tried to send you a short video but this does not allow me to do that...as I said, when I click on the username field, the keyboard option appears only for a split second then disappears with only the cancel button showing. I can email you the video if you give me an email address to send it to.

**Comment by Kemmey** [comment]
@frjps I believe you :-D 

What version of iOS and watchOS are you running?

Does the watch properly show in control center that it is connected to the watch? 

Does handover work properly between watch and phone? When you're on the login screen, the watch should offer up the FAQ page to the phone - so if you're on the login screen, and then on your phone enter the app switcher, it should show a small safari icon at the bottom with a text something like "from your Apple Watch" - does that work?

**Comment by frjps** [comment]
I am using iOS 14 beta & watchOS 7 beta but I don’t have that issue with any other app so I didn’t make that connection. Could very well be the problem. If I restart the watch & touch the username field, it will show me the keyboard long enough for me to enter that info, but then it won’t show the keyboard again for me to enter the password. I hope I don’t have to wait for the beta to be open for Apple to fix this as I love this watch app…it’s actually the most useful one to me! No luck with the handover either…just doesn’t show on my app switcher on the phone. Any other ideas? If not, I’ll just have to wait but 🙄….wish Apple wouldn’t break things 😂.

**Comment by Kemmey** [comment]
@frjps Ah - that explains it! 

When reporting bugs from beta releases, always mention that, as it is highly relevant. 

SwiftUI in watchOS 7 is extremely unstable, and because of this I've put off work on watchOS 7 support, to allow the beta to mature. It's just not worth my limited time right now. 

I'm currently focused on finishing up 1.0.6 - once that hits the store, I'll get to work on next gen stuff :-D

**Comment by frjps** [comment]
OK. Thanks for letting me know.

**Comment by remimarents** [comment]
Same problem- but once I was presented with the option to choose login from keychain, but it disappeared again. Please let me know if there’s a workaround! Thanks

**Comment by Kemmey** [comment]
This should have been fixed in watchOS7/iOS14 beta 4 - closing for now
