### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by thumbmaster** [Kemmey/Kemmey-TeslaWatch-Public#70]
This is not an "issue" but an observation. I am running the latest beta on my Series 5 GPS while my wife has the release version on her identical watch. The beta is easily 4-10x faster on almost all functions. 😃

**Comment by Kemmey** [comment]
@thumbmaster Though I would love to celebrate, I'm certain that is mostly down to network connectivity on the watches. One watch might have a stronger connection to the paired phone, or it might have no connection and is roaming on WiFi. 

The speed of action execution completely depend on whether the vehicle has been initially woken up. Once awake and the polling is running regularly, then action executes should be pretty much instantaneous, given network conditions...

And I've not changed any code that I can blame for any speed increase, unfortunately. 

But hey - put the beta on both watches and see if you can reproduce? :-D

**Comment by thumbmaster** [comment]
To clarify the circumstances: we were both at home within strong wifi coverage. The car is at the driveway (decent wifi). We in the same room inside the house. I just installed the app on her watch and was showing her how it works. Normally, with the beta app, my watch would wake up the car from sleep in no more than 2-3 seconds. On her watch, it took well over 5 seconds. In any case, I'll put beta on her watch to see if it improves.
