### ISSUE TITLE
Watch Face

### ISSUE THREAD

**Issue by DJBARTUK** [Kemmey/Kemmey-TeslaWatch-Public#72]
I have a first edition Apple Watch. App is working but can’t set my face to look like the photo on image 1 in the App Store. I can add it as a corner complication but can’t see it in the watch faces to select? I’m on iOS  13.6 on phone and watch is running 6.2.6 and is a model AT1803.

**Comment by Kemmey** [comment]
Hey @DJBARTUK 

That Watch face is exclusive to Apple Watch series 4 and 5, unfortunately.

**Comment by DJBARTUK** [comment]
Time for a birthday update then 👍🥳

**Comment by Kemmey** [comment]
Wait for series 6 in three months! :-D

**Comment by DJBARTUK** [comment]
What will waiting for the series 6 gain me app wise? 🤓

**Comment by Kemmey** [comment]
Nothing that I know of now - but new and shiny is always better! :-D

**Comment by DJBARTUK** [comment]
![4798738B-9734-468D-9781-6AA3B42F09D7](https://user-images.githubusercontent.com/68914618/88914876-36b65f80-d25b-11ea-81d0-f0dd557f0316.png)

Grabbed an Apple Watch Series 5 to use the app and both phone and watch are updated but getting the purchased message on the App Store so unable to re install?

**Comment by DJBARTUK** [comment]
All sorted Ive redownloaded via the watch app but still can’t activate the watch face

**Comment by Kemmey** [comment]
@DJBARTUK Congrats on the new Watch! It's awesome with the always on screen! :-D 

The watch face I'm using for the store screenshot is the Infograph watch face. It supports four complications in the center and four on the outside. It's super information dense - and put the Tesla app complication in one of the corners for the most information in any complication from the app.
