### ISSUE TITLE
Vents windows button and auto refresh on whilst charging?

### ISSUE THREAD

**Issue by 11ELON** [Kemmey/Kemmey-TeslaWatch-Public#75]
Great App for the Apple Watch, I have the other two apps from another two developers, the Tesla Watch App is simply to use. Just want to know if I can request the following changes:

1. For Model S owners, we currently don’t have the vents windows function with our cars, can we please modify the button to another feature?

2. Once the Tesla is plugged in and charging, any chance can the Tesla Watch App automatically switched the Background updates to On with the lowest 15 minutes interval? And perhaps allow wake in background as well? Once the charging stopped or unplugged the app automatically switches off the Background Updates and allow wake in background off?

**Comment by Kemmey** [comment]
Thanks! That's high praise!

1. Is implemented in the current beta ( https://testflight.apple.com/join/FdzFOLZv ), in that you now get vent sunroof. Vent windows is still there, as I've not been able to determine if no model s vehicles can do it or just some. I'll hide vent windows for model s if it's a generic thing

2. The current App Store release will already do that. It refreshes every 15 mins while charging - after the first initial update where charging is detected. I'll actually modify that to 5 mins while supercharging as that makes more sense. I can't enable background only while charging, as that would upset the people who definitely don't want background updates to wake the car under no circumstances. But you can kind of get it by setting the interval to 5hrs and then manually wake the app once when you start charging to detect the charging state - then subsequent updates will be in 15 mins intervals as long as it's charging. 

Hope that makes sense :-D

**Comment by 11ELON** [comment]
Based on Tesla owners reports:

Model 3 can vent and close, Model X can only vent and Model S cannot do anything. Also Tesla got rid of the sunroof option towards the end of 2018 so anything from 2019 is all fixed glass roof. 

I currently switched off both the Background updates and Allow wake in background for the Tesla Watch App as I try to avoid Phantom drains. 

Would there be any summon buttons available for future release?

**Comment by Kemmey** [comment]
Hey - sorry, I missed your summon question. 

This has been previously discussed - TL;DR; - no. 

Longer answer - summon doesn't work properly in europe where I live, I don't have fsd to test out, and support in the apis seems to be on their way out - prioritizing a bluetooth approach to confirm driver presence.
