### ISSUE TITLE
More frequent updates while charging ?

### ISSUE THREAD

**Issue by samiruk** [Kemmey/Kemmey-TeslaWatch-Public#77]
It would be great if we could get much quicker updates while charging. Would be nice to know quickly and accurately what percentage the vehicle is charged to and how long to go. Is this possible ?

**Comment by Kemmey** [comment]
The background update budget is 50 updates per 24 hours. 

Currently, it will update every 15 minutes while charging - but only after charging has been detected by an update - so first load can take up to the normal interval. 

I'll update so it will background update every 5 mins while supercharging. 

Remember, that if you manually launch the app and let it refresh so it shows charging, then background updates will be in the quick interval. So if you want to keep an eye on charging, just launch the app once and then rely on the complication :-D

**Comment by samiruk** [comment]
Great thanks
