### ISSUE TITLE
Can't login on Watch OS7

### ISSUE THREAD

**Issue by ismailatt** [Kemmey/Kemmey-TeslaWatch-Public#82]
Hi,

I just get a blank screen when I try to login. No keyboard prompt on watch or iPhone. They are both connected to each other and I followed advice from other posts about similar login issues. Using Watch OS7 and Ios14 latest public beta.  

I tried restarting both devices and deleting and installing app again directly from AW. Keychain briefly showed up but then disappeared again.

**Comment by Kemmey** [comment]
Hey. watchOS 7 is not currently working as swiftui and continuity keyboard are broken. 

I just got word this morning that yesterday's ios14 release seems to have fixed it - so if you can, try the dev beta - or wait till it releases as public. 

Just FYI - even I as dev don't run the betas on main hardware. It's not worth it.

**Comment by ismailatt** [comment]
Thank you! I’ll report back once I update to latest update. And definitely avoiding beta in future 😅

**Comment by emekerd** [comment]
It wouldn’t let me login, so I deleted the app and now I can’t reinstall it.

**Comment by remimarents** [comment]
Latest WatchOS beta fixed it! Now I am playing happily along. Ps using TestFlight beta also.

**Comment by ismailatt** [comment]
Works now after latest watch is beta update. Thank you!
