### ISSUE TITLE
App won’t reinstall

### ISSUE THREAD

**Issue by emekerd** [Kemmey/Kemmey-TeslaWatch-Public#83]
Hi, i was having trouble logging in to the app. So i deleted it. Now it won’t reinstall from App Store. The reinstall cloud is not there... 

I deleted app because it would not bring up keyboard to type in password.

**Comment by Kemmey** [comment]
You have to do it from the watch: https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/5

Check you phone is not on do not disturb - in that case, manually check Notification Center for the continuity keyboard notification. 

Also note the app doesn't work with the iOS 14 / watchOS 7 betas.

**Comment by emekerd** [comment]
Thank you!
