### ISSUE TITLE
App is on loop and unsuable

### ISSUE THREAD

**Issue by jasonhermosa** [Kemmey/Kemmey-TeslaWatch-Public#86]
Tried restarting devices and closing app. Emailed video to developer feedback through Testflight.

**Comment by Kemmey** [comment]
@jasonhermosa Thanks! Got the video - I'll investigate. Could you hop into TestFlight and skip back a few versions and see if that fixes it? My best guess is that your token is invalid but not expired - you get bumped to the login screen, which checks to see that you have a token - and then sends you back - only to return to login screen. 

I've recently reworked that logic - must be a bug in there - so REALLY good that you've hit it and reported it before it ships to the store!

**Comment by Kemmey** [comment]
Did you change your password recently, by any chance? That would invalidate all tokens.

**Comment by Kemmey** [comment]
@jasonhermosa did any of the recent betas fix the loop problem?

**Comment by jasonhermosa** [comment]
Hi. I forgot to reply to this. I rolled back to 207 and that stopped the loop. I installed the latest one you released yesterday and that seems to be working as well. I was able to re-enter my credentials and I'm able to use it now. 

Jason Hermosa

**Comment by Kemmey** [comment]
Fantastic! Thank you!

Fingers crossed it's properly solved. I'll close the issue for now.
