### ISSUE TITLE
Release notes not scrolling

### ISSUE THREAD

**Issue by nachtbraker** [Kemmey/Kemmey-TeslaWatch-Public#88]
Just loaded v227. The release notes appear immediately after first running the app, but do not scroll at all. (So in a way, the choppy release notes scrolling is indeed fixed. 🤓)

**Comment by nachtbraker** [comment]
So this is all I see: 
![IMG_2205](https://user-images.githubusercontent.com/29022937/89741705-c518b580-da93-11ea-8212-3c3621805f5b.png)

Scrolling with the crown wheel or by swiping doesn't work.

**Comment by nachtbraker** [comment]
If I dismiss this screen and go to settings->Changelog, scrolling works fine.

**Comment by Kemmey** [comment]
Interesting. They scrolled just fine on my s5 44mm 10 mins ago. 

Which watch do you have?

Thank you for the quick feedback - I'll definitely have to sort that out before release!

**Comment by nachtbraker** [comment]
It's an old one, gen2. Model MP062ZD/A. Running 6.2.8.

**Comment by nachtbraker** [comment]
I just loaded v230. Scrolling the initial release notes screen worked fine now. 👍
