### ISSUE TITLE
Tesla Battery size not recognised

### ISSUE THREAD

**Issue by allanbretta** [Kemmey/Kemmey-TeslaWatch-Public#94]
Hi. I downloaded the app and all works well other than the app appears to not recognize the battery size of the car (75kwh)
Therefore the mileage for the car is overstated; watch shows 90% 266miles - car & phone app show 90% 212 miles. 
Cheers Allan.

**Comment by Kemmey** [comment]
Duplicate of https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/40

This is fixed in current beta and shipping very soon to the store
