### ISSUE TITLE
Request; option to change the three default actions?

### ISSUE THREAD

**Issue by TheKingNL** [Kemmey/Kemmey-TeslaWatch-Public#96]
Great app. One question. Would it be possible to offer the users an option to choose the three actions that are displayed on the first screen?

Now I have climate/Frunk/Lock.

I would like to be able to change it. I often need to unlock the chargeport so that is one that I would like to have on the screen by default. 

Thanks!

**Comment by Kemmey** [comment]
Hey - yeah, absolutely - that's one of my highest priorities for 1.0.7 once 1.0.6 ships to the store. 

Be aware that tapping the unlock button will also unlock the charge port, if the charging cable is connected :-D

**Comment by Kemmey** [comment]
And that you can press hard on the screen to get an additional four fast access menu items, which vary based on current car state - but unlock port should be one of them in any given situation

**Comment by TheKingNL** [comment]
Ah, great! Keep up the good work! Really like the app. Tried some others in the past but this app is definately the best.

**Comment by Kemmey** [comment]
Fixed in released 1.0.7
